autd3: autd::gain::holo::Holo Class Reference
autd::gain::holo::Holo Class Reference
Gain to produce multiple focal points.
#include <holo.hpp>
Public Member Functions
Holo (BackendPtr backend, std::vector< core::Vector3 > foci, const std::vector< double > &amps)
~Holo () override=default
Holo (const Holo &v) noexcept=default
Holo & operator= (const Holo &obj)=default
Holo (Holo &&obj)=default
Holo & operator= (Holo &&obj)=default
BackendPtr & backend ()
std::vector< core::Vector3 > & foci ()
std::vector< complex > & amplitudes ()
Public Member Functions inherited from autd::core::Gain
virtual void calc (const GeometryPtr &geometry)
Calculate duty ratio and phase of each transducer.
void build (const GeometryPtr &geometry)
Initialize data and call calc().
void rebuild (const GeometryPtr &geometry)
Re-calculate duty ratio and phase of each transducer.
std::vector< DataArray > & data ()
Getter function for the data of duty ratio and phase of each transducers.
Gain () noexcept
virtual ~Gain ()=default
Gain (const Gain &v) noexcept=default
Gain & operator= (const Gain &obj)=default
Gain (Gain &&obj)=default
Gain & operator= (Gain &&obj)=default
Additional Inherited Members
Static Public Member Functions inherited from autd::core::Gain
static GainPtr create ()
Generate empty gain.
Detailed Description
Gain to produce multiple focal points.
Definition at line 27 of file holo.hpp.
Constructor & Destructor Documentation
Holo() [1/3]
autd::gain::holo::Holo::Holo (BackendPtr backend, std::vector< core::Vector3 > foci, const std::vector< double > & amps) inline
Definition at line 29 of file holo.hpp.
~Holo()
autd::gain::holo::Holo::~Holo () override default
Holo() [2/3]
autd::gain::holo::Holo::Holo (const Holo & v) default noexcept
Holo() [3/3]
autd::gain::holo::Holo::Holo (Holo && obj) default
Member Function Documentation
amplitudes()
std::vector<complex>& autd::gain::holo::Holo::amplitudes () inline
Definition at line 42 of file holo.hpp.
backend()
BackendPtr& autd::gain::holo::Holo::backend () inline
Definition at line 40 of file holo.hpp.
Referenced by autd::gain::holo::SDP::create(), autd::gain::holo::EVD::create(), autd::gain::holo::Naive::create(), autd::gain::holo::GS::create(), and autd::gain::holo::GSPAT::create().
foci()
std::vector<core::Vector3>& autd::gain::holo::Holo::foci () inline
Definition at line 41 of file holo.hpp.
Referenced by autd::gain::holo::SDP::create(), autd::gain::holo::EVD::create(), autd::gain::holo::Naive::create(), autd::gain::holo::GS::create(), autd::gain::holo::GSPAT::create(), and autd::gain::holo::Greedy::create().
operator=() [1/2]
Holo& autd::gain::holo::Holo::operator= (const Holo & obj) default
operator=() [2/2]
Holo& autd::gain::holo::Holo::operator= (Holo && obj) default
The documentation for this class was generated from the following file:
include/autd3/gain/holo.hpp