autd3: autd::_utils::Quaternion< T > Class Template Reference
autd::_utils::Quaternion< T > Class Template Reference
Simple quaternion class.
#include <quaternion.hpp>
Public Member Functions
Quaternion ()=default
Quaternion (T w, T x, T y, T z)
Quaternion (T w, const Vector3< T > &v)
Quaternion (const Quaternion &v)=default
Quaternion & operator= (const Quaternion &obj)=default
Vector3< T > & v () noexcept
const Vector3< T > & v () const noexcept
T & x () noexcept
T & y () noexcept
T & z () noexcept
T & w () noexcept
const T & x () const noexcept
const T & y () const noexcept
const T & z () const noexcept
const T & w () const noexcept
T l2_norm_squared () const
T l2_norm () const
T norm () const
Quaternion normalized () const
Quaternion conjugate () const
Quaternion inverse () const
Quaternion & operator+= (const Quaternion &rhs)
Quaternion & operator-= (const Quaternion &rhs)
Quaternion & operator*= (T rhs)
Quaternion & operator/= (T rhs)
Static Public Member Functions
static Quaternion AngleAxis (T a, const Vector3< T > &v)
Friends
Quaternion operator* (Quaternion lhs, const Quaternion &rhs)
Vector3< T > operator* (Quaternion lhs, const Vector3< T > &rhs)
template<typename Ts >
std::ostream & operator<< (std::ostream &, const Quaternion< Ts > &)
template<typename Ts >
bool operator== (const Quaternion< Ts > &lhs, const Quaternion< Ts > &rhs)
template<typename Ts >
bool operator!= (const Quaternion< Ts > &lhs, const Quaternion< Ts > &rhs)
Quaternion operator+ (Quaternion lhs, const Quaternion &rhs)
Quaternion operator- (Quaternion lhs, const Quaternion &rhs)
Quaternion operator* (Quaternion lhs, const T &rhs)
Quaternion operator* (const T &lhs, Quaternion rhs)
Quaternion operator/ (Quaternion lhs, const T &rhs)
Detailed Description
template<typename T>
class autd::_utils::Quaternion< T >
Simple quaternion class.
Definition at line 23 of file quaternion.hpp.
Constructor & Destructor Documentation
Quaternion() [1/4]
template<typename T > autd::_utils::Quaternion< T >::Quaternion () default
Referenced by autd::_utils::Quaternion< T >::AngleAxis().
Quaternion() [2/4]
template<typename T > autd::_utils::Quaternion< T >::Quaternion (T w, T x, T y, T z) inline
Definition at line 30 of file quaternion.hpp.
References autd::_utils::Quaternion< T >::w(), autd::_utils::Quaternion< T >::x(), autd::_utils::Quaternion< T >::y(), and autd::_utils::Quaternion< T >::z().
Quaternion() [3/4]
template<typename T > autd::_utils::Quaternion< T >::Quaternion (T w, const Vector3< T > & v) inline
Definition at line 34 of file quaternion.hpp.
References autd::_utils::Quaternion< T >::v(), and autd::_utils::Quaternion< T >::w().
Quaternion() [4/4]
template<typename T > autd::_utils::Quaternion< T >::Quaternion (const Quaternion< T > & v) default
Member Function Documentation
AngleAxis()
template<typename T > static Quaternion autd::_utils::Quaternion< T >::AngleAxis (T a, const Vector3< T > & v) inline static
Definition at line 79 of file quaternion.hpp.
References autd::_utils::Quaternion< T >::normalized(), autd::_utils::Quaternion< T >::Quaternion(), and autd::_utils::Quaternion< T >::v().
Referenced by autd::AngleAxis().
conjugate()
template<typename T > Quaternion autd::_utils::Quaternion< T >::conjugate () const inline
Definition at line 57 of file quaternion.hpp.
Referenced by autd::_utils::Quaternion< T >::inverse().
inverse()
template<typename T > Quaternion autd::_utils::Quaternion< T >::inverse () const inline
Definition at line 63 of file quaternion.hpp.
References autd::_utils::Quaternion< T >::conjugate(), and autd::_utils::Quaternion< T >::l2_norm_squared().
l2_norm()
template<typename T > T autd::_utils::Quaternion< T >::l2_norm () const inline
Definition at line 53 of file quaternion.hpp.
References autd::_utils::Quaternion< T >::l2_norm_squared().
Referenced by autd::_utils::Quaternion< T >::norm(), and autd::_utils::Quaternion< T >::normalized().
l2_norm_squared()
template<typename T > T autd::_utils::Quaternion< T >::l2_norm_squared () const inline
Definition at line 52 of file quaternion.hpp.
References autd::_utils::VectorX< T >::l2_norm_squared().
Referenced by autd::_utils::Quaternion< T >::inverse(), and autd::_utils::Quaternion< T >::l2_norm().
norm()
template<typename T > T autd::_utils::Quaternion< T >::norm () const inline
Definition at line 54 of file quaternion.hpp.
References autd::_utils::Quaternion< T >::l2_norm().
normalized()
template<typename T > Quaternion autd::_utils::Quaternion< T >::normalized () const inline
Definition at line 56 of file quaternion.hpp.
References autd::_utils::Quaternion< T >::l2_norm().
Referenced by autd::_utils::Quaternion< T >::AngleAxis().
operator*=()
template<typename T > Quaternion& autd::_utils::Quaternion< T >::operator*= (T rhs) inline
Definition at line 107 of file quaternion.hpp.
operator+=()
template<typename T > Quaternion& autd::_utils::Quaternion< T >::operator+= (const Quaternion< T > & rhs) inline
Definition at line 97 of file quaternion.hpp.
References autd::_utils::Quaternion< T >::v(), and autd::_utils::Quaternion< T >::w().
operator-=()
template<typename T > Quaternion& autd::_utils::Quaternion< T >::operator-= (const Quaternion< T > & rhs) inline
Definition at line 102 of file quaternion.hpp.
References autd::_utils::Quaternion< T >::v(), and autd::_utils::Quaternion< T >::w().
operator/=()
template<typename T > Quaternion& autd::_utils::Quaternion< T >::operator/= (T rhs) inline
Definition at line 112 of file quaternion.hpp.
operator=()
template<typename T > Quaternion& autd::_utils::Quaternion< T >::operator= (const Quaternion< T > & obj) default
v() [1/2]
template<typename T > const Vector3<T>& autd::_utils::Quaternion< T >::v () const inline noexcept
Definition at line 42 of file quaternion.hpp.
v() [2/2]
template<typename T > Vector3<T>& autd::_utils::Quaternion< T >::v () inline noexcept
Definition at line 41 of file quaternion.hpp.
Referenced by autd::_utils::Quaternion< T >::AngleAxis(), autd::_utils::Quaternion< T >::operator+=(), autd::_utils::Quaternion< T >::operator-=(), autd::_utils::operator==(), and autd::_utils::Quaternion< T >::Quaternion().
w() [1/2]
template<typename T > const T& autd::_utils::Quaternion< T >::w () const inline noexcept
Definition at line 50 of file quaternion.hpp.
w() [2/2]
template<typename T > T& autd::_utils::Quaternion< T >::w () inline noexcept
Definition at line 46 of file quaternion.hpp.
Referenced by autd::_utils::Quaternion< T >::operator+=(), autd::_utils::Quaternion< T >::operator-=(), autd::_utils::operator<<(), autd::_utils::operator==(), autd::_utils::Quaternion< T >::Quaternion(), and autd::_utils::Matrix4x4< T >::Translation().
x() [1/2]
template<typename T > const T& autd::_utils::Quaternion< T >::x () const inline noexcept
Definition at line 47 of file quaternion.hpp.
References autd::_utils::Vector3< T >::x().
x() [2/2]
template<typename T > T& autd::_utils::Quaternion< T >::x () inline noexcept
Definition at line 43 of file quaternion.hpp.
References autd::_utils::Vector3< T >::x().
Referenced by autd::_utils::operator<<(), autd::_utils::Quaternion< T >::Quaternion(), and autd::_utils::Matrix4x4< T >::Translation().
y() [1/2]
template<typename T > const T& autd::_utils::Quaternion< T >::y () const inline noexcept
Definition at line 48 of file quaternion.hpp.
References autd::_utils::Vector3< T >::y().
y() [2/2]
template<typename T > T& autd::_utils::Quaternion< T >::y () inline noexcept
Definition at line 44 of file quaternion.hpp.
References autd::_utils::Vector3< T >::y().
Referenced by autd::_utils::operator<<(), autd::_utils::Quaternion< T >::Quaternion(), and autd::_utils::Matrix4x4< T >::Translation().
z() [1/2]
template<typename T > const T& autd::_utils::Quaternion< T >::z () const inline noexcept
Definition at line 49 of file quaternion.hpp.
References autd::_utils::Vector3< T >::z().
z() [2/2]
template<typename T > T& autd::_utils::Quaternion< T >::z () inline noexcept
Definition at line 45 of file quaternion.hpp.
References autd::_utils::Vector3< T >::z().
Referenced by autd::_utils::operator<<(), autd::_utils::Quaternion< T >::Quaternion(), and autd::_utils::Matrix4x4< T >::Translation().
Friends And Related Function Documentation
operator!=
template<typename T > template<typename Ts > bool operator!= (const Quaternion< Ts > & lhs, const Quaternion< Ts > & rhs) friend
operator* [1/4]
template<typename T > Quaternion operator* (const T & lhs, Quaternion< T > rhs) friend
Definition at line 130 of file quaternion.hpp.
operator* [2/4]
template<typename T > Quaternion operator* (Quaternion< T > lhs, const Quaternion< T > & rhs) friend
Definition at line 65 of file quaternion.hpp.
operator* [3/4]
template<typename T > Quaternion operator* (Quaternion< T > lhs, const T & rhs) friend
Definition at line 126 of file quaternion.hpp.
operator* [4/4]
template<typename T > Vector3<T> operator* (Quaternion< T > lhs, const Vector3< T > & rhs) friend
Definition at line 73 of file quaternion.hpp.
operator+
template<typename T > Quaternion operator+ (Quaternion< T > lhs, const Quaternion< T > & rhs) friend
Definition at line 118 of file quaternion.hpp.
operator-
template<typename T > Quaternion operator- (Quaternion< T > lhs, const Quaternion< T > & rhs) friend
Definition at line 122 of file quaternion.hpp.
operator/
template<typename T > Quaternion operator/ (Quaternion< T > lhs, const T & rhs) friend
Definition at line 134 of file quaternion.hpp.
operator<<
template<typename T > template<typename Ts > std::ostream& operator<< (std::ostream & , const Quaternion< Ts > &) friend
operator==
template<typename T > template<typename Ts > bool operator== (const Quaternion< Ts > & lhs, const Quaternion< Ts > & rhs) friend
The documentation for this class was generated from the following file:
include/linalg/quaternion.hpp