autd3: autd::gain::holo::HoloGain< B > Class Template Reference
autd::gain::holo::HoloGain< B > Class Template Reference final
Gain to produce multiple focal points.
#include <holo.hpp>
Public Member Functions
void Build () override
Calculate amplitude and phase of each transducer.
HoloGain (std::vector< Vector3 > foci, std::vector< Float > amps, const OPT_METHOD method=OPT_METHOD::SDP, void *params=nullptr)
~HoloGain () override=default
HoloGain (const HoloGain &v) noexcept=default
HoloGain & operator= (const HoloGain &obj)=default
HoloGain (HoloGain &&obj)=default
HoloGain & operator= (HoloGain &&obj)=default
std::vector< Vector3 > & foci ()
std::vector< Float > & amplitudes ()
void Rebuild ()
Public Member Functions inherited from autd::gain::Gain
void SetGeometry (const GeometryPtr &geometry) noexcept
Set AUTD Geometry which is required to build gain.
GeometryPtr geometry () const noexcept
Get AUTD Geometry.
std::vector< AUTDDataArray > & data ()
Getter function for the data of amplitude and phase of each transducers.
Gain () noexcept
virtual ~Gain ()=default
Gain (const Gain &v) noexcept=default
Gain & operator= (const Gain &obj)=default
Gain (Gain &&obj)=default
Gain & operator= (Gain &&obj)=default
Static Public Member Functions
static std::shared_ptr< HoloGain > Create (const std::vector< Vector3 > &foci, const std::vector< Float > &amps, OPT_METHOD method=OPT_METHOD::SDP, void *params=nullptr)
Generate function.
Static Public Member Functions inherited from autd::gain::Gain
static GainPtr Create ()
Generate empty gain.
Detailed Description
template<typename B>
class autd::gain::holo::HoloGain< B >
Gain to produce multiple focal points.
Definition at line 91 of file holo.hpp.
Constructor & Destructor Documentation
HoloGain() [1/3]
template<typename B > autd::gain::holo::HoloGain< B >::HoloGain (std::vector< Vector3 > foci, std::vector< Float > amps, const OPT_METHOD method = OPT_METHOD::SDP, void * params = nullptr) inline
Definition at line 135 of file holo.hpp.
~HoloGain()
template<typename B > autd::gain::holo::HoloGain< B >::~HoloGain () override default
HoloGain() [2/3]
template<typename B > autd::gain::holo::HoloGain< B >::HoloGain (const HoloGain< B > & v) default noexcept
HoloGain() [3/3]
template<typename B > autd::gain::holo::HoloGain< B >::HoloGain (HoloGain< B > && obj) default
Member Function Documentation
amplitudes()
template<typename B > std::vector<Float>& autd::gain::holo::HoloGain< B >::amplitudes () inline
Definition at line 144 of file holo.hpp.
Build()
template<typename B > void autd::gain::holo::HoloGain< B >::Build () inline override virtual
Calculate amplitude and phase of each transducer.
Reimplemented from autd::gain::Gain.
Definition at line 106 of file holo.hpp.
References autd::gain::CheckAndInit(), autd::gain::holo::EVD, autd::gain::Gain::geometry(), autd::gain::holo::GS, autd::gain::holo::GSPAT, autd::gain::holo::LM, autd::gain::holo::NAIVE, and autd::gain::holo::SDP.
Referenced by autd::gain::holo::HoloGain< B >::Rebuild().
Create()
template<typename B > static std::shared_ptr<HoloGain> autd::gain::holo::HoloGain< B >::Create (const std::vector< Vector3 > & foci, const std::vector< Float > & amps, OPT_METHOD method = OPT_METHOD::SDP, void * params = nullptr) inline static
Generate function.
Parameters
[in] foci focal points
[in] amps amplitudes of the foci
[in] method optimization method. see also OPT_METHOD
[in] params pointer to optimization parameters
Definition at line 100 of file holo.hpp.
References autd::gain::holo::HoloGain< B >::foci().
foci()
template<typename B > std::vector<Vector3>& autd::gain::holo::HoloGain< B >::foci () inline
Definition at line 143 of file holo.hpp.
Referenced by autd::gain::holo::HoloGain< B >::Create().
operator=() [1/2]
template<typename B > HoloGain& autd::gain::holo::HoloGain< B >::operator= (const HoloGain< B > & obj) default
operator=() [2/2]
template<typename B > HoloGain& autd::gain::holo::HoloGain< B >::operator= (HoloGain< B > && obj) default
Rebuild()
template<typename B > void autd::gain::holo::HoloGain< B >::Rebuild () inline
Definition at line 145 of file holo.hpp.
References autd::gain::holo::HoloGain< B >::Build().
The documentation for this class was generated from the following file:
include/gain/holo.hpp