autd3: autd::_utils::Matrix4x4< T > Class Template Reference
autd::_utils::Matrix4x4< T > Class Template Reference
#include <matrix.hpp>
Public Member Functions
Matrix4x4 ()
Matrix4x4 & operator+= (const Matrix4x4 &rhs)
Matrix4x4 & operator-= (const Matrix4x4 &rhs)
Matrix4x4 & operator*= (const T &rhs)
Matrix4x4 & operator/= (const T &rhs)
Matrix4x4 operator- () const
Public Member Functions inherited from autd::_utils::MatrixX< T >
MatrixX (const size_t row, const size_t col)
MatrixX (const MatrixX &obj)
MatrixX & operator= (const MatrixX &obj)
T & at (const size_t row, const size_t col)
const T & at (const size_t row, const size_t col) const
T & operator() (const size_t row, const size_t col)
const T & operator() (const size_t row, const size_t col) const
T * data ()
const T * data () const
size_t rows () const noexcept
size_t cols () const noexcept
size_t size () const noexcept
VectorX< T > col (const size_t idx) const noexcept
VectorX< T > row (const size_t idx) const noexcept
MatrixX & operator+= (const MatrixX &rhs)
MatrixX & operator-= (const MatrixX &rhs)
MatrixX & operator*= (T rhs)
MatrixX & operator/= (T rhs)
MatrixX operator- () const
Static Public Member Functions
static Matrix4x4 Translation (const Vector3< T > &v, const Quaternion< T > &q)
Static Public Member Functions inherited from autd::_utils::MatrixX< T >
static MatrixX Zero (size_t row, size_t col)
static MatrixX Identity (const size_t row, const size_t col)
Friends
Matrix4x4 operator+ (const Matrix4x4 &lhs, const Matrix4x4 &rhs)
Matrix4x4 operator- (const Matrix4x4 &lhs, const Matrix4x4 &rhs)
Matrix4x4 operator* (const Matrix4x4 &lhs, const T &rhs)
Matrix4x4 operator* (const T &lhs, Matrix4x4 rhs)
Matrix4x4 operator/ (const Matrix4x4 &lhs, const T &rhs)
Detailed Description
template<typename T>
class autd::_utils::Matrix4x4< T >
Definition at line 120 of file matrix.hpp.
Constructor & Destructor Documentation
Matrix4x4()
template<typename T > autd::_utils::Matrix4x4< T >::Matrix4x4 () inline
Definition at line 122 of file matrix.hpp.
Member Function Documentation
operator*=()
template<typename T > Matrix4x4& autd::_utils::Matrix4x4< T >::operator*= (const T & rhs) inline
Definition at line 126 of file matrix.hpp.
operator+=()
template<typename T > Matrix4x4& autd::_utils::Matrix4x4< T >::operator+= (const Matrix4x4< T > & rhs) inline
Definition at line 124 of file matrix.hpp.
operator-()
template<typename T > Matrix4x4 autd::_utils::Matrix4x4< T >::operator- () const inline
Definition at line 129 of file matrix.hpp.
operator-=()
template<typename T > Matrix4x4& autd::_utils::Matrix4x4< T >::operator-= (const Matrix4x4< T > & rhs) inline
Definition at line 125 of file matrix.hpp.
operator/=()
template<typename T > Matrix4x4& autd::_utils::Matrix4x4< T >::operator/= (const T & rhs) inline
Definition at line 127 of file matrix.hpp.
Translation()
template<typename T > static Matrix4x4 autd::_utils::Matrix4x4< T >::Translation (const Vector3< T > & v, const Quaternion< T > & q) inline static
Definition at line 138 of file matrix.hpp.
References autd::_utils::Quaternion< T >::w(), autd::_utils::Quaternion< T >::x(), autd::_utils::Vector3< T >::x(), autd::_utils::Quaternion< T >::y(), autd::_utils::Vector3< T >::y(), autd::_utils::Quaternion< T >::z(), and autd::_utils::Vector3< T >::z().
Referenced by autd::Translation().
Friends And Related Function Documentation
operator* [1/2]
template<typename T > Matrix4x4 operator* (const Matrix4x4< T > & lhs, const T & rhs) friend
Definition at line 134 of file matrix.hpp.
operator* [2/2]
template<typename T > Matrix4x4 operator* (const T & lhs, Matrix4x4< T > rhs) friend
Definition at line 135 of file matrix.hpp.
operator+
template<typename T > Matrix4x4 operator+ (const Matrix4x4< T > & lhs, const Matrix4x4< T > & rhs) friend
Definition at line 131 of file matrix.hpp.
operator-
template<typename T > Matrix4x4 operator- (const Matrix4x4< T > & lhs, const Matrix4x4< T > & rhs) friend
Definition at line 133 of file matrix.hpp.
operator/
template<typename T > Matrix4x4 operator/ (const Matrix4x4< T > & lhs, const T & rhs) friend
Definition at line 136 of file matrix.hpp.
The documentation for this class was generated from the following file:
include/linalg/matrix.hpp