autd3: autd::_utils::Vector3< T > Class Template Reference
autd::_utils::Vector3< T > Class Template Reference
#include <vector.hpp>
Public Member Functions
Vector3 ()
Vector3 (T x, T y, T z)
T & x () noexcept
T & y () noexcept
T & z () noexcept
const T & x () const noexcept
const T & y () const noexcept
const T & z () const noexcept
Vector3 normalized () const
Vector3 cross (const Vector3 &rhs) const
T angle (const Vector3 &v) const
Vector3 & operator+= (const Vector3 &rhs)
Vector3 & operator-= (const Vector3 &rhs)
Vector3 & operator*= (const T &rhs)
Vector3 & operator/= (const T &rhs)
Vector3 operator- () const
Public Member Functions inherited from autd::_utils::VectorX< T >
VectorX (const size_t size)
VectorX (const VectorX &obj)
VectorX & operator= (const VectorX &obj)
T l2_norm_squared () const
T l2_norm () const
T norm () const
void normalize ()
VectorX & normalized () const
T dot (const VectorX &rhs) const
T & at (size_t i)
const T & at (size_t i) const
T & operator() (size_t i)
const T & operator() (size_t i) const
T * data ()
const T * data () const
size_t size () const noexcept
VectorX & operator+= (const VectorX &rhs)
VectorX & operator-= (const VectorX &rhs)
VectorX & operator*= (T rhs)
VectorX & operator/= (T rhs)
VectorX operator- () const
Static Public Member Functions
static Vector3 UnitX ()
static Vector3 UnitY ()
static Vector3 UnitZ ()
static Vector3 Zero ()
Static Public Member Functions inherited from autd::_utils::VectorX< T >
static VectorX Zero (size_t size)
static VectorX Ones (size_t size)
Friends
Vector3 operator+ (const Vector3 &lhs, const Vector3 &rhs)
Vector3 operator- (const Vector3 &lhs, const Vector3 &rhs)
Vector3 operator* (const Vector3 &lhs, const T &rhs)
Vector3 operator* (const T &lhs, const Vector3 &rhs)
Vector3 operator/ (const Vector3 &lhs, const T &rhs)
Detailed Description
template<typename T>
class autd::_utils::Vector3< T >
Definition at line 106 of file vector.hpp.
Constructor & Destructor Documentation
Vector3() [1/2]
template<typename T > autd::_utils::Vector3< T >::Vector3 () inline
Definition at line 108 of file vector.hpp.
Vector3() [2/2]
template<typename T > autd::_utils::Vector3< T >::Vector3 (T x, T y, T z) inline
Definition at line 109 of file vector.hpp.
Member Function Documentation
angle()
template<typename T > T autd::_utils::Vector3< T >::angle (const Vector3< T > & v) const inline
Definition at line 133 of file vector.hpp.
cross()
template<typename T > Vector3 autd::_utils::Vector3< T >::cross (const Vector3< T > & rhs) const inline
Definition at line 129 of file vector.hpp.
normalized()
template<typename T > Vector3 autd::_utils::Vector3< T >::normalized () const inline
Definition at line 127 of file vector.hpp.
operator*=()
template<typename T > Vector3& autd::_utils::Vector3< T >::operator*= (const T & rhs) inline
Definition at line 146 of file vector.hpp.
operator+=()
template<typename T > Vector3& autd::_utils::Vector3< T >::operator+= (const Vector3< T > & rhs) inline
Definition at line 144 of file vector.hpp.
operator-()
template<typename T > Vector3 autd::_utils::Vector3< T >::operator- () const inline
Definition at line 149 of file vector.hpp.
operator-=()
template<typename T > Vector3& autd::_utils::Vector3< T >::operator-= (const Vector3< T > & rhs) inline
Definition at line 145 of file vector.hpp.
operator/=()
template<typename T > Vector3& autd::_utils::Vector3< T >::operator/= (const T & rhs) inline
Definition at line 147 of file vector.hpp.
UnitX()
template<typename T > static Vector3 autd::_utils::Vector3< T >::UnitX () inline static
Definition at line 122 of file vector.hpp.
UnitY()
template<typename T > static Vector3 autd::_utils::Vector3< T >::UnitY () inline static
Definition at line 123 of file vector.hpp.
UnitZ()
template<typename T > static Vector3 autd::_utils::Vector3< T >::UnitZ () inline static
Definition at line 124 of file vector.hpp.
x() [1/2]
template<typename T > const T& autd::_utils::Vector3< T >::x () const inline noexcept
Definition at line 118 of file vector.hpp.
x() [2/2]
template<typename T > T& autd::_utils::Vector3< T >::x () inline noexcept
Definition at line 115 of file vector.hpp.
Referenced by autd::_utils::Vector3< Float >::cross(), autd::_utils::Matrix4x4< T >::Translation(), and autd::_utils::Quaternion< T >::x().
y() [1/2]
template<typename T > const T& autd::_utils::Vector3< T >::y () const inline noexcept
Definition at line 119 of file vector.hpp.
y() [2/2]
template<typename T > T& autd::_utils::Vector3< T >::y () inline noexcept
Definition at line 116 of file vector.hpp.
Referenced by autd::_utils::Vector3< Float >::cross(), autd::_utils::Matrix4x4< T >::Translation(), and autd::_utils::Quaternion< T >::y().
z() [1/2]
template<typename T > const T& autd::_utils::Vector3< T >::z () const inline noexcept
Definition at line 120 of file vector.hpp.
z() [2/2]
template<typename T > T& autd::_utils::Vector3< T >::z () inline noexcept
Definition at line 117 of file vector.hpp.
Referenced by autd::_utils::Vector3< Float >::cross(), autd::_utils::Matrix4x4< T >::Translation(), and autd::_utils::Quaternion< T >::z().
Zero()
template<typename T > static Vector3 autd::_utils::Vector3< T >::Zero () inline static
Definition at line 125 of file vector.hpp.
Friends And Related Function Documentation
operator* [1/2]
template<typename T > Vector3 operator* (const T & lhs, const Vector3< T > & rhs) friend
Definition at line 155 of file vector.hpp.
operator* [2/2]
template<typename T > Vector3 operator* (const Vector3< T > & lhs, const T & rhs) friend
Definition at line 154 of file vector.hpp.
operator+
template<typename T > Vector3 operator+ (const Vector3< T > & lhs, const Vector3< T > & rhs) friend
Definition at line 151 of file vector.hpp.
operator-
template<typename T > Vector3 operator- (const Vector3< T > & lhs, const Vector3< T > & rhs) friend
Definition at line 153 of file vector.hpp.
operator/
template<typename T > Vector3 operator/ (const Vector3< T > & lhs, const T & rhs) friend
Definition at line 156 of file vector.hpp.
The documentation for this class was generated from the following file:
include/linalg/vector.hpp