autd3: autd::_utils Namespace Reference
autd::_utils Namespace Reference
Classes
class _Helper
class Matrix4x4
struct MatrixX
class Quaternion
Simple quaternion class.
class Vector3
class Vector4
struct VectorX
Functions
template<typename T >
std::ostream & operator<< (std::ostream &os, const MatrixX< T > &obj)
template<typename T >
bool operator== (const MatrixX< T > &lhs, const MatrixX< T > &rhs)
template<typename T >
bool operator!= (const MatrixX< T > &lhs, const MatrixX< T > &rhs)
template<typename T >
std::ostream & operator<< (std::ostream &os, const Quaternion< T > &obj)
template<typename T >
bool operator== (const Quaternion< T > &lhs, const Quaternion< T > &rhs)
template<typename T >
bool operator!= (const Quaternion< T > &lhs, const Quaternion< T > &rhs)
template<typename T >
std::ostream & operator<< (std::ostream &os, const VectorX< T > &obj)
template<typename T >
bool operator== (const VectorX< T > &lhs, const VectorX< T > &rhs)
template<typename T >
bool operator!= (const VectorX< T > &lhs, const VectorX< T > &rhs)
Function Documentation
operator!=() [1/3]
template<typename T > bool autd::_utils::operator!= (const MatrixX< T > & lhs, const MatrixX< T > & rhs)
Definition at line 115 of file matrix.hpp.
operator!=() [2/3]
template<typename T > bool autd::_utils::operator!= (const Quaternion< T > & lhs, const Quaternion< T > & rhs)
Definition at line 150 of file quaternion.hpp.
operator!=() [3/3]
template<typename T > bool autd::_utils::operator!= (const VectorX< T > & lhs, const VectorX< T > & rhs)
Definition at line 101 of file vector.hpp.
operator<<() [1/3]
template<typename T > std::ostream& autd::_utils::operator<< (std::ostream & os, const MatrixX< T > & obj)
Definition at line 107 of file matrix.hpp.
References autd::_utils::_Helper::mat_show().
operator<<() [2/3]
template<typename T > std::ostream& autd::_utils::operator<< (std::ostream & os, const Quaternion< T > & obj)
Definition at line 141 of file quaternion.hpp.
References autd::_utils::Quaternion< T >::w(), autd::_utils::Quaternion< T >::x(), autd::_utils::Quaternion< T >::y(), and autd::_utils::Quaternion< T >::z().
operator<<() [3/3]
template<typename T > std::ostream& autd::_utils::operator<< (std::ostream & os, const VectorX< T > & obj)
Definition at line 93 of file vector.hpp.
operator==() [1/3]
template<typename T > bool autd::_utils::operator== (const MatrixX< T > & lhs, const MatrixX< T > & rhs)
Definition at line 111 of file matrix.hpp.
References autd::_utils::_Helper::mat_equals().
operator==() [2/3]
template<typename T > bool autd::_utils::operator== (const Quaternion< T > & lhs, const Quaternion< T > & rhs)
Definition at line 146 of file quaternion.hpp.
References autd::_utils::Quaternion< T >::v(), and autd::_utils::Quaternion< T >::w().
operator==() [3/3]
template<typename T > bool autd::_utils::operator== (const VectorX< T > & lhs, const VectorX< T > & rhs)
Definition at line 97 of file vector.hpp.