autd3: autd::core::Device Struct Reference
autd::core::Device Struct Reference
Device contains an AUTD device geometry.
#include <geometry.hpp>
Static Public Member Functions
static Device create (const Vector3 &position, const Quaternion &quaternion)
static Device create (const Vector3 &position, const Vector3 &euler_angles)
Public Attributes
Vector3 x_direction
Vector3 y_direction
Vector3 z_direction
std::unique_ptr< Vector3[]> global_trans_positions
Eigen::Transform< double, 3, Eigen::Affine > g2l
Detailed Description
Device contains an AUTD device geometry.
Definition at line 51 of file geometry.hpp.
Member Function Documentation
create() [1/2]
static Device autd::core::Device::create (const Vector3 & position, const Quaternion & quaternion) inline static
Definition at line 52 of file geometry.hpp.
References global_trans_positions, autd::core::is_missing_transducer(), autd::core::NUM_TRANS_IN_UNIT, autd::core::NUM_TRANS_X, autd::core::NUM_TRANS_Y, autd::core::TRANS_SPACING_MM, x_direction, y_direction, and z_direction.
Referenced by autd::core::Geometry::add_device(), and create().
create() [2/2]
static Device autd::core::Device::create (const Vector3 & position, const Vector3 & euler_angles) inline static
Definition at line 72 of file geometry.hpp.
References create().
Member Data Documentation
g2l
Eigen::Transform<double, 3, Eigen::Affine> autd::core::Device::g2l
Definition at line 83 of file geometry.hpp.
global_trans_positions
std::unique_ptr<Vector3[]> autd::core::Device::global_trans_positions
Definition at line 82 of file geometry.hpp.
Referenced by create().
x_direction
Vector3 autd::core::Device::x_direction
Definition at line 79 of file geometry.hpp.
Referenced by create().
y_direction
Vector3 autd::core::Device::y_direction
Definition at line 80 of file geometry.hpp.
Referenced by create().
z_direction
Vector3 autd::core::Device::z_direction
Definition at line 81 of file geometry.hpp.
Referenced by create().
The documentation for this struct was generated from the following file:
include/autd3/core/geometry.hpp