autd3: autd::_utils::VectorX< T > Struct Template Reference
autd::_utils::VectorX< T > Struct Template Reference
#include <vector.hpp>
Public Member Functions
VectorX (const size_t size)
VectorX (const VectorX &obj)
VectorX & operator= (const VectorX &obj)
T l2_norm_squared () const
T l2_norm () const
T norm () const
void normalize ()
VectorX & normalized () const
T dot (const VectorX &rhs) const
T & at (size_t i)
const T & at (size_t i) const
T & operator() (size_t i)
const T & operator() (size_t i) const
T * data ()
const T * data () const
size_t size () const noexcept
VectorX & operator+= (const VectorX &rhs)
VectorX & operator-= (const VectorX &rhs)
VectorX & operator*= (T rhs)
VectorX & operator/= (T rhs)
VectorX operator- () const
Static Public Member Functions
static VectorX Zero (size_t size)
static VectorX Ones (size_t size)
Friends
template<typename Ts >
std::ostream & operator<< (std::ostream &, const VectorX< Ts > &)
template<typename Ts >
bool operator== (const VectorX< Ts > &lhs, const VectorX< Ts > &rhs)
template<typename Ts >
bool operator!= (const VectorX< Ts > &lhs, const VectorX< Ts > &rhs)
VectorX operator+ (const VectorX &lhs, const VectorX &rhs)
VectorX operator- (const VectorX &lhs, const VectorX &rhs)
VectorX operator* (const VectorX &lhs, const T &rhs)
VectorX operator* (const T &lhs, const VectorX &rhs)
VectorX operator/ (const VectorX &lhs, const T &rhs)
Detailed Description
template<typename T>
struct autd::_utils::VectorX< T >
Definition at line 27 of file vector.hpp.
Constructor & Destructor Documentation
VectorX() [1/2]
template<typename T > autd::_utils::VectorX< T >::VectorX (const size_t size) inline explicit
Definition at line 29 of file vector.hpp.
VectorX() [2/2]
template<typename T > autd::_utils::VectorX< T >::VectorX (const VectorX< T > & obj) inline
Definition at line 30 of file vector.hpp.
Member Function Documentation
at() [1/2]
template<typename T > T& autd::_utils::VectorX< T >::at (size_t i) inline
Definition at line 57 of file vector.hpp.
at() [2/2]
template<typename T > const T& autd::_utils::VectorX< T >::at (size_t i) const inline
Definition at line 58 of file vector.hpp.
data() [1/2]
template<typename T > T* autd::_utils::VectorX< T >::data () inline
Definition at line 63 of file vector.hpp.
Referenced by autd::_utils::VectorX< Float >::operator=(), autd::_utils::MatrixX< T >::row(), autd::_utils::VectorX< Float >::VectorX(), and autd::_utils::VectorX< Float >::Zero().
data() [2/2]
template<typename T > const T* autd::_utils::VectorX< T >::data () const inline
Definition at line 64 of file vector.hpp.
dot()
template<typename T > T autd::_utils::VectorX< T >::dot (const VectorX< T > & rhs) const inline
Definition at line 55 of file vector.hpp.
l2_norm()
template<typename T > T autd::_utils::VectorX< T >::l2_norm () const inline
Definition at line 37 of file vector.hpp.
Referenced by autd::_utils::Vector3< Float >::angle(), autd::_utils::VectorX< Float >::norm(), autd::_utils::VectorX< Float >::normalize(), and autd::_utils::VectorX< Float >::normalized().
l2_norm_squared()
template<typename T > T autd::_utils::VectorX< T >::l2_norm_squared () const inline
Definition at line 36 of file vector.hpp.
Referenced by autd::_utils::VectorX< Float >::l2_norm(), and autd::_utils::Quaternion< T >::l2_norm_squared().
norm()
template<typename T > T autd::_utils::VectorX< T >::norm () const inline
Definition at line 38 of file vector.hpp.
normalize()
template<typename T > void autd::_utils::VectorX< T >::normalize () inline
Definition at line 40 of file vector.hpp.
normalized()
template<typename T > VectorX& autd::_utils::VectorX< T >::normalized () const inline
Definition at line 41 of file vector.hpp.
Ones()
template<typename T > static VectorX autd::_utils::VectorX< T >::Ones (size_t size) inline static
Definition at line 49 of file vector.hpp.
operator()() [1/2]
template<typename T > T& autd::_utils::VectorX< T >::operator() (size_t i) inline
Definition at line 60 of file vector.hpp.
operator()() [2/2]
template<typename T > const T& autd::_utils::VectorX< T >::operator() (size_t i) const inline
Definition at line 61 of file vector.hpp.
operator*=()
template<typename T > VectorX& autd::_utils::VectorX< T >::operator*= (T rhs) inline
Definition at line 76 of file vector.hpp.
operator+=()
template<typename T > VectorX& autd::_utils::VectorX< T >::operator+= (const VectorX< T > & rhs) inline
Definition at line 74 of file vector.hpp.
operator-()
template<typename T > VectorX autd::_utils::VectorX< T >::operator- () const inline
Definition at line 79 of file vector.hpp.
operator-=()
template<typename T > VectorX& autd::_utils::VectorX< T >::operator-= (const VectorX< T > & rhs) inline
Definition at line 75 of file vector.hpp.
operator/=()
template<typename T > VectorX& autd::_utils::VectorX< T >::operator/= (T rhs) inline
Definition at line 77 of file vector.hpp.
operator=()
template<typename T > VectorX& autd::_utils::VectorX< T >::operator= (const VectorX< T > & obj) inline
Definition at line 31 of file vector.hpp.
size()
template<typename T > size_t autd::_utils::VectorX< T >::size () const inline noexcept
Definition at line 66 of file vector.hpp.
Referenced by autd::_utils::VectorX< Float >::Ones(), autd::_utils::VectorX< Float >::VectorX(), and autd::_utils::VectorX< Float >::Zero().
Zero()
template<typename T > static VectorX autd::_utils::VectorX< T >::Zero (size_t size) inline static
Definition at line 43 of file vector.hpp.
Friends And Related Function Documentation
operator!=
template<typename T > template<typename Ts > bool operator!= (const VectorX< Ts > & lhs, const VectorX< Ts > & rhs) friend
operator* [1/2]
template<typename T > VectorX operator* (const T & lhs, const VectorX< T > & rhs) friend
Definition at line 84 of file vector.hpp.
operator* [2/2]
template<typename T > VectorX operator* (const VectorX< T > & lhs, const T & rhs) friend
Definition at line 83 of file vector.hpp.
operator+
template<typename T > VectorX operator+ (const VectorX< T > & lhs, const VectorX< T > & rhs) friend
Definition at line 81 of file vector.hpp.
operator-
template<typename T > VectorX operator- (const VectorX< T > & lhs, const VectorX< T > & rhs) friend
Definition at line 82 of file vector.hpp.
operator/
template<typename T > VectorX operator/ (const VectorX< T > & lhs, const T & rhs) friend
Definition at line 85 of file vector.hpp.
operator<<
template<typename T > template<typename Ts > std::ostream& operator<< (std::ostream & , const VectorX< Ts > &) friend
operator==
template<typename T > template<typename Ts > bool operator== (const VectorX< Ts > & lhs, const VectorX< Ts > & rhs) friend
The documentation for this struct was generated from the following file:
include/linalg/vector.hpp