autd3: autd::_utils::MatrixX< T > Struct Template Reference
autd::_utils::MatrixX< T > Struct Template Reference
#include <matrix.hpp>
Public Member Functions
MatrixX (const size_t row, const size_t col)
MatrixX (const MatrixX &obj)
MatrixX & operator= (const MatrixX &obj)
T & at (const size_t row, const size_t col)
const T & at (const size_t row, const size_t col) const
T & operator() (const size_t row, const size_t col)
const T & operator() (const size_t row, const size_t col) const
T * data ()
const T * data () const
size_t rows () const noexcept
size_t cols () const noexcept
size_t size () const noexcept
VectorX< T > col (const size_t idx) const noexcept
VectorX< T > row (const size_t idx) const noexcept
MatrixX & operator+= (const MatrixX &rhs)
MatrixX & operator-= (const MatrixX &rhs)
MatrixX & operator*= (T rhs)
MatrixX & operator/= (T rhs)
MatrixX operator- () const
Static Public Member Functions
static MatrixX Zero (size_t row, size_t col)
static MatrixX Identity (const size_t row, const size_t col)
Friends
template<typename Ts >
std::ostream & operator<< (std::ostream &, const MatrixX< Ts > &)
template<typename Ts >
bool operator== (const MatrixX< Ts > &lhs, const MatrixX< Ts > &rhs)
template<typename Ts >
bool operator!= (const MatrixX< Ts > &lhs, const MatrixX< Ts > &rhs)
MatrixX operator+ (const MatrixX &lhs, const MatrixX &rhs)
MatrixX operator- (const MatrixX &lhs, const MatrixX &rhs)
MatrixX operator* (const MatrixX &lhs, const T &rhs)
MatrixX operator* (const T &lhs, const MatrixX &rhs)
MatrixX operator/ (const MatrixX &lhs, const T &rhs)
VectorX< T > operator* (const MatrixX &lhs, const VectorX< T > &rhs)
Detailed Description
template<typename T>
struct autd::_utils::MatrixX< T >
Definition at line 25 of file matrix.hpp.
Constructor & Destructor Documentation
MatrixX() [1/2]
template<typename T > autd::_utils::MatrixX< T >::MatrixX (const size_t row, const size_t col) inline
Definition at line 27 of file matrix.hpp.
References autd::_utils::MatrixX< T >::col(), and autd::_utils::MatrixX< T >::row().
MatrixX() [2/2]
template<typename T > autd::_utils::MatrixX< T >::MatrixX (const MatrixX< T > & obj) inline
Definition at line 28 of file matrix.hpp.
References autd::_utils::MatrixX< T >::data(), and autd::_utils::MatrixX< T >::size().
Member Function Documentation
at() [1/2]
template<typename T > T& autd::_utils::MatrixX< T >::at (const size_t row, const size_t col) inline
Definition at line 51 of file matrix.hpp.
References autd::_utils::MatrixX< T >::col(), and autd::_utils::MatrixX< T >::row().
Referenced by autd::_utils::MatrixX< T >::col().
at() [2/2]
template<typename T > const T& autd::_utils::MatrixX< T >::at (const size_t row, const size_t col) const inline
Definition at line 52 of file matrix.hpp.
References autd::_utils::MatrixX< T >::col(), and autd::_utils::MatrixX< T >::row().
col()
template<typename T > VectorX<T> autd::_utils::MatrixX< T >::col (const size_t idx) const inline noexcept
Definition at line 64 of file matrix.hpp.
References autd::_utils::MatrixX< T >::at().
Referenced by autd::_utils::MatrixX< T >::at(), autd::_utils::MatrixX< T >::Identity(), autd::_utils::MatrixX< T >::MatrixX(), autd::_utils::MatrixX< T >::operator()(), and autd::_utils::MatrixX< T >::Zero().
cols()
template<typename T > size_t autd::_utils::MatrixX< T >::cols () const inline noexcept
Definition at line 61 of file matrix.hpp.
data() [1/2]
template<typename T > T* autd::_utils::MatrixX< T >::data () inline
Definition at line 57 of file matrix.hpp.
Referenced by autd::_utils::MatrixX< T >::MatrixX(), autd::_utils::MatrixX< T >::operator=(), and autd::_utils::MatrixX< T >::Zero().
data() [2/2]
template<typename T > const T* autd::_utils::MatrixX< T >::data () const inline
Definition at line 58 of file matrix.hpp.
Identity()
template<typename T > static MatrixX autd::_utils::MatrixX< T >::Identity (const size_t row, const size_t col) inline static
Definition at line 45 of file matrix.hpp.
References autd::_utils::MatrixX< T >::col(), autd::_utils::MatrixX< T >::row(), and autd::_utils::MatrixX< T >::Zero().
operator()() [1/2]
template<typename T > T& autd::_utils::MatrixX< T >::operator() (const size_t row, const size_t col) inline
Definition at line 54 of file matrix.hpp.
References autd::_utils::MatrixX< T >::col(), and autd::_utils::MatrixX< T >::row().
operator()() [2/2]
template<typename T > const T& autd::_utils::MatrixX< T >::operator() (const size_t row, const size_t col) const inline
Definition at line 55 of file matrix.hpp.
References autd::_utils::MatrixX< T >::col(), and autd::_utils::MatrixX< T >::row().
operator*=()
template<typename T > MatrixX& autd::_utils::MatrixX< T >::operator*= (T rhs) inline
Definition at line 87 of file matrix.hpp.
operator+=()
template<typename T > MatrixX& autd::_utils::MatrixX< T >::operator+= (const MatrixX< T > & rhs) inline
Definition at line 85 of file matrix.hpp.
operator-()
template<typename T > MatrixX autd::_utils::MatrixX< T >::operator- () const inline
Definition at line 90 of file matrix.hpp.
operator-=()
template<typename T > MatrixX& autd::_utils::MatrixX< T >::operator-= (const MatrixX< T > & rhs) inline
Definition at line 86 of file matrix.hpp.
operator/=()
template<typename T > MatrixX& autd::_utils::MatrixX< T >::operator/= (T rhs) inline
Definition at line 88 of file matrix.hpp.
operator=()
template<typename T > MatrixX& autd::_utils::MatrixX< T >::operator= (const MatrixX< T > & obj) inline
Definition at line 33 of file matrix.hpp.
References autd::_utils::MatrixX< T >::data(), and autd::_utils::MatrixX< T >::size().
row()
template<typename T > VectorX<T> autd::_utils::MatrixX< T >::row (const size_t idx) const inline noexcept
Definition at line 72 of file matrix.hpp.
References autd::_utils::VectorX< T >::data().
Referenced by autd::_utils::MatrixX< T >::at(), autd::_utils::MatrixX< T >::Identity(), autd::_utils::MatrixX< T >::MatrixX(), autd::_utils::MatrixX< T >::operator()(), and autd::_utils::MatrixX< T >::Zero().
rows()
template<typename T > size_t autd::_utils::MatrixX< T >::rows () const inline noexcept
Definition at line 60 of file matrix.hpp.
size()
template<typename T > size_t autd::_utils::MatrixX< T >::size () const inline noexcept
Definition at line 62 of file matrix.hpp.
Referenced by autd::_utils::MatrixX< T >::MatrixX(), autd::_utils::MatrixX< T >::operator=(), and autd::_utils::MatrixX< T >::Zero().
Zero()
template<typename T > static MatrixX autd::_utils::MatrixX< T >::Zero (size_t row, size_t col) inline static
Definition at line 38 of file matrix.hpp.
References autd::_utils::MatrixX< T >::col(), autd::_utils::MatrixX< T >::data(), autd::_utils::MatrixX< T >::row(), and autd::_utils::MatrixX< T >::size().
Referenced by autd::_utils::MatrixX< T >::Identity().
Friends And Related Function Documentation
operator!=
template<typename T > template<typename Ts > bool operator!= (const MatrixX< Ts > & lhs, const MatrixX< Ts > & rhs) friend
operator* [1/3]
template<typename T > MatrixX operator* (const MatrixX< T > & lhs, const T & rhs) friend
Definition at line 94 of file matrix.hpp.
operator* [2/3]
template<typename T > VectorX<T> operator* (const MatrixX< T > & lhs, const VectorX< T > & rhs) friend
Definition at line 98 of file matrix.hpp.
operator* [3/3]
template<typename T > MatrixX operator* (const T & lhs, const MatrixX< T > & rhs) friend
Definition at line 95 of file matrix.hpp.
operator+
template<typename T > MatrixX operator+ (const MatrixX< T > & lhs, const MatrixX< T > & rhs) friend
Definition at line 92 of file matrix.hpp.
operator-
template<typename T > MatrixX operator- (const MatrixX< T > & lhs, const MatrixX< T > & rhs) friend
Definition at line 93 of file matrix.hpp.
operator/
template<typename T > MatrixX operator/ (const MatrixX< T > & lhs, const T & rhs) friend
Definition at line 96 of file matrix.hpp.
operator<<
template<typename T > template<typename Ts > std::ostream& operator<< (std::ostream & , const MatrixX< Ts > &) friend
operator==
template<typename T > template<typename Ts > bool operator== (const MatrixX< Ts > & lhs, const MatrixX< Ts > & rhs) friend
The documentation for this struct was generated from the following file:
include/linalg/matrix.hpp