autd3: autd::core::Logic Class Reference
autd::core::Logic Class Reference
Firmware logic.
#include <logic.hpp>
Static Public Member Functions
static uint8_t get_id ()
Get unique message id.
static bool is_msg_processed (const size_t num_devices, const uint8_t msg_id, const uint8_t *const rx)
check if the data which have msg_id have been processed in the devices.
static void pack_header (const uint8_t msg_id, const uint8_t fpga_ctrl_flag, const uint8_t cpu_ctrl_flag, uint8_t *const data)
Pack header with message id.
static uint8_t pack_header (const ModulationPtr &mod, const uint8_t fpga_ctrl_flag, const uint8_t cpu_ctrl_flag, uint8_t *const data)
Pack header with modulation data.
static size_t pack_body (const GainPtr &gain, uint8_t *data)
Pack data body which contain phase and duty data of each transducer.
static size_t pack_body (const PointSequencePtr &seq, const GeometryPtr &geometry, uint8_t *data)
Pack data body with sequence data.
static size_t pack_body (const GainSequencePtr &seq, const GeometryPtr &geometry, uint8_t *data)
Pack data body with sequence data.
static size_t pack_delay_offset_body (const std::vector< std::array< uint8_t, NUM_TRANS_IN_UNIT >> &delay, const std::vector< std::array< uint8_t, NUM_TRANS_IN_UNIT >> &offset, uint8_t *data)
Pack data body to set output delay and enable.
Detailed Description
Firmware logic.
Definition at line 28 of file logic.hpp.
Member Function Documentation
get_id()
static uint8_t autd::core::Logic::get_id () inline static
Get unique message id.
Returns
message id
Definition at line 34 of file logic.hpp.
References autd::core::MSG_NORMAL_BASE.
Referenced by pack_header().
is_msg_processed()
static bool autd::core::Logic::is_msg_processed (const size_t num_devices, const uint8_t msg_id, const uint8_t *const rx) inline static
check if the data which have msg_id have been processed in the devices.
Parameters
num_devices number of devices
msg_id message id
rx pointer to received data
Returns
whether the data have been processed
Definition at line 50 of file logic.hpp.
pack_body() [1/3]
static size_t autd::core::Logic::pack_body (const GainPtr & gain, uint8_t * data) inline static
Pack data body which contain phase and duty data of each transducer.
Parameters
gain Gain
[out] data pointer to transmission data
Returns
size_t size to send
This function must be called after pack_header
Definition at line 111 of file logic.hpp.
References autd::core::GlobalHeader::cpu_ctrl_flags, autd::core::NUM_TRANS_IN_UNIT, and autd::core::WRITE_BODY.
pack_body() [2/3]
static size_t autd::core::Logic::pack_body (const GainSequencePtr & seq, const GeometryPtr & geometry, uint8_t * data) inline static
Pack data body with sequence data.
Parameters
seq Sequence
geometry Geometry
[out] data pointer to transmission data
Returns
size_t size to send
This function must be called after pack_header
Definition at line 173 of file logic.hpp.
References autd::core::GlobalHeader::cpu_ctrl_flags, autd::core::DUTY_PHASE_FULL, autd::core::NUM_TRANS_IN_UNIT, autd::core::PHASE_FULL, autd::core::PHASE_HALF, autd::core::SEQ_BEGIN, autd::core::SEQ_END, and autd::core::WRITE_BODY.
pack_body() [3/3]
static size_t autd::core::Logic::pack_body (const PointSequencePtr & seq, const GeometryPtr & geometry, uint8_t * data) inline static
Pack data body with sequence data.
Parameters
seq Sequence
geometry Geometry
[out] data pointer to transmission data
Returns
size_t size to send
This function must be called after pack_header
Definition at line 132 of file logic.hpp.
References autd::core::GlobalHeader::cpu_ctrl_flags, autd::core::NUM_TRANS_IN_UNIT, autd::core::SEQ_BEGIN, autd::core::SEQ_END, autd::core::SeqFocus::set(), and autd::core::WRITE_BODY.
pack_delay_offset_body()
static size_t autd::core::Logic::pack_delay_offset_body (const std::vector< std::array< uint8_t, NUM_TRANS_IN_UNIT >> & delay, const std::vector< std::array< uint8_t, NUM_TRANS_IN_UNIT >> & offset, uint8_t * data) inline static
Pack data body to set output delay and enable.
Parameters
delay delay data of each transducer
offset duty offset data of each transducer
[out] data pointer to transmission data
Returns
size_t size to send
This function must be called after pack_header
Definition at line 234 of file logic.hpp.
References autd::core::GlobalHeader::cpu_ctrl_flags, autd::core::NUM_TRANS_IN_UNIT, autd::core::utils::pack_to_u16(), and autd::core::WRITE_BODY.
pack_header() [1/2]
static uint8_t autd::core::Logic::pack_header (const ModulationPtr & mod, const uint8_t fpga_ctrl_flag, const uint8_t cpu_ctrl_flag, uint8_t *const data) inline static
Pack header with modulation data.
Parameters
mod Modulation
fpga_ctrl_flag fpga control flag
cpu_ctrl_flag cpu control flag
[out] data pointer to transmission data
Returns
message id
Definition at line 80 of file logic.hpp.
References autd::core::GlobalHeader::cpu_ctrl_flags, get_id(), autd::core::MOD_BEGIN, autd::core::MOD_END, autd::core::MOD_FRAME_SIZE, and pack_header().
pack_header() [2/2]
static void autd::core::Logic::pack_header (const uint8_t msg_id, const uint8_t fpga_ctrl_flag, const uint8_t cpu_ctrl_flag, uint8_t *const data) inline static
Pack header with message id.
Parameters
msg_id message id
fpga_ctrl_flag fpga control flag
cpu_ctrl_flag cpu control flag
[out] data pointer to transmission data
Definition at line 64 of file logic.hpp.
References autd::core::GlobalHeader::msg_id.
Referenced by pack_header().
The documentation for this class was generated from the following file:
include/autd3/core/logic.hpp