autd3: autd::core::TxDatagram Class Reference
autd::core::TxDatagram Class Reference final
TxDatagram represents the data sent to devices.
#include <hardware_defined.hpp>
Public Member Functions
TxDatagram ()
TxDatagram (const size_t device_num)
const uint8_t * data () const
const GlobalHeader * header () const
const Body * body (const size_t i) const
uint8_t * data ()
GlobalHeader * header ()
Body * body (const size_t i)
size_t header_size () const
size_t body_size () const
size_t num_bodies () const
size_t & num_bodies ()
size_t size () const
void copy_from (const TxDatagram &other)
Detailed Description
TxDatagram represents the data sent to devices.
Definition at line 144 of file hardware_defined.hpp.
Constructor & Destructor Documentation
TxDatagram() [1/2]
autd::core::TxDatagram::TxDatagram () inline
Definition at line 146 of file hardware_defined.hpp.
TxDatagram() [2/2]
autd::core::TxDatagram::TxDatagram (const size_t device_num) inline explicit
Definition at line 148 of file hardware_defined.hpp.
Member Function Documentation
body() [1/2]
Body* autd::core::TxDatagram::body (const size_t i) inline
Definition at line 158 of file hardware_defined.hpp.
body() [2/2]
const Body* autd::core::TxDatagram::body (const size_t i) const inline
Definition at line 154 of file hardware_defined.hpp.
Referenced by autd::core::DelayOffsets::pack(), autd::core::Gain::pack(), autd::core::PointSequence::pack(), and autd::core::GainSequence::pack().
body_size()
size_t autd::core::TxDatagram::body_size () const inline
Definition at line 161 of file hardware_defined.hpp.
Referenced by copy_from().
copy_from()
void autd::core::TxDatagram::copy_from (const TxDatagram & other) inline
Definition at line 167 of file hardware_defined.hpp.
References body_size(), data(), header_size(), and num_bodies().
data() [1/2]
uint8_t* autd::core::TxDatagram::data () inline
Definition at line 156 of file hardware_defined.hpp.
data() [2/2]
const uint8_t* autd::core::TxDatagram::data () const inline
Definition at line 152 of file hardware_defined.hpp.
Referenced by copy_from(), autd::core::datagram::CommonHeader::pack(), autd::core::datagram::SpecialMessageIdHeader::pack(), autd::core::datagram::SilentStepHeader::pack(), and autd::core::Modulation::pack().
header() [1/2]
GlobalHeader* autd::core::TxDatagram::header () inline
Definition at line 157 of file hardware_defined.hpp.
header() [2/2]
const GlobalHeader* autd::core::TxDatagram::header () const inline
Definition at line 153 of file hardware_defined.hpp.
Referenced by autd::core::DelayOffsets::pack(), autd::core::Gain::pack(), autd::core::PointSequence::pack(), and autd::core::GainSequence::pack().
header_size()
size_t autd::core::TxDatagram::header_size () const inline
Definition at line 160 of file hardware_defined.hpp.
Referenced by copy_from().
num_bodies() [1/2]
size_t& autd::core::TxDatagram::num_bodies () inline
Definition at line 163 of file hardware_defined.hpp.
num_bodies() [2/2]
size_t autd::core::TxDatagram::num_bodies () const inline
Definition at line 162 of file hardware_defined.hpp.
Referenced by copy_from(), autd::core::datagram::CommonHeader::pack(), autd::core::DelayOffsets::pack(), autd::core::datagram::SpecialMessageIdHeader::pack(), autd::core::Gain::pack(), autd::core::datagram::SilentStepHeader::pack(), autd::core::Modulation::pack(), autd::core::datagram::NullBody::pack(), autd::core::PointSequence::pack(), and autd::core::GainSequence::pack().
size()
size_t autd::core::TxDatagram::size () const inline
Definition at line 165 of file hardware_defined.hpp.
The documentation for this class was generated from the following file:
include/autd3/core/hardware_defined.hpp