autd3: autd::core::PointSequence Class Reference
autd::core::PointSequence Class Reference
PointSequence provides a function to display the focus sequentially and periodically.
#include <sequence.hpp>
Classes
class StreamCommaInputPS
Public Member Functions
PointSequence () noexcept
size_t size () const override
void add (const Vector3 &point, const uint8_t duty=0xFF)
Add control point.
void add (const std::vector< Vector3 > &points, std::vector< uint8_t > &duties)
Add control points.
const std::vector< Vector3 > & control_points () const
const std::vector< uint8_t > & duties () const
void init () override
void pack (const Geometry &geometry, TxDatagram &tx) override
bool is_finished () const override
StreamCommaInputPS operator<< (const Vector3 &point)
Public Member Functions inherited from autd::core::Sequence
Sequence ()
~Sequence () override=default
Sequence (const Sequence &v) noexcept=delete
Sequence & operator= (const Sequence &obj)=delete
Sequence (Sequence &&obj)=default
Sequence & operator= (Sequence &&obj)=default
double set_frequency (const double freq)
Set frequency of the sequence.
double frequency () const
size_t period_us () const
double sampling_freq () const
size_t sampling_period_us () const noexcept
size_t & sampling_freq_div_ratio () noexcept
size_t sampling_freq_div_ratio () const noexcept
bool wait_on_sync () const noexcept
If true, the output will be start after synchronization.
bool & wait_on_sync () noexcept
If true, the output will be start after synchronization.
Public Member Functions inherited from autd::core::datagram::IDatagramBody
IDatagramBody ()=default
virtual ~IDatagramBody ()=default
IDatagramBody (const IDatagramBody &v) noexcept=delete
IDatagramBody & operator= (const IDatagramBody &obj)=delete
IDatagramBody (IDatagramBody &&obj)=default
IDatagramBody & operator= (IDatagramBody &&obj)=default
Detailed Description
PointSequence provides a function to display the focus sequentially and periodically.
PointSequence uses a timer on the FPGA to ensure that the focus is precisely timed. PointSequence currently has the following three limitations.
The maximum number of control points is autd::core::POINT_SEQ_BUFFER_SIZE_MAX.
The sampling interval of control points is an integer multiple of 25us and less than or equal to 25us x autd::core::SEQ_SAMPLING_FREQ_DIV_MAX.
Only a single focus can be displayed at a certain moment.
Definition at line 111 of file sequence.hpp.
Constructor & Destructor Documentation
PointSequence()
autd::core::PointSequence::PointSequence () inline noexcept
Definition at line 136 of file sequence.hpp.
Member Function Documentation
add() [1/2]
void autd::core::PointSequence::add (const std::vector< Vector3 > & points, std::vector< uint8_t > & duties) inline
Add control points.
Parameters
[in] points control points
[in] duties duty ratios
duties.resize(points.size(), 0xFF) will be called.
Definition at line 160 of file sequence.hpp.
References duties(), and autd::core::POINT_SEQ_BUFFER_SIZE_MAX.
add() [2/2]
void autd::core::PointSequence::add (const Vector3 & point, const uint8_t duty = 0xFF) inline
Add control point.
Parameters
[in] point control point
[in] duty duty ratio
Definition at line 145 of file sequence.hpp.
References autd::core::POINT_SEQ_BUFFER_SIZE_MAX.
Referenced by autd::core::PointSequence::StreamCommaInputPS::operator,(), autd::core::PointSequence::StreamCommaInputPS::operator<<(), and operator<<().
control_points()
const std::vector<Vector3>& autd::core::PointSequence::control_points () const inline
Returns
std::vector<Vector3> Control points of the sequence
Definition at line 176 of file sequence.hpp.
duties()
const std::vector<uint8_t>& autd::core::PointSequence::duties () const inline
Returns
std::vector<uint8_t> Duty ratios of the sequence
Definition at line 181 of file sequence.hpp.
Referenced by add().
init()
void autd::core::PointSequence::init () inline override virtual
Implements autd::core::datagram::IDatagramBody.
Definition at line 183 of file sequence.hpp.
is_finished()
bool autd::core::PointSequence::is_finished () const inline override virtual
Implements autd::core::datagram::IDatagramBody.
Definition at line 224 of file sequence.hpp.
Referenced by pack().
operator<<()
StreamCommaInputPS autd::core::PointSequence::operator<< (const Vector3 & point) inline
Definition at line 249 of file sequence.hpp.
References add().
pack()
void autd::core::PointSequence::pack (const Geometry & geometry, TxDatagram & tx) inline override virtual
Implements autd::core::datagram::IDatagramBody.
Definition at line 185 of file sequence.hpp.
References autd::core::TxDatagram::body(), autd::core::GlobalHeader::cpu_ctrl_flags, autd::core::TxDatagram::header(), is_finished(), autd::core::TxDatagram::num_bodies(), autd::core::Geometry::num_devices(), autd::core::NUM_TRANS_IN_UNIT, autd::core::OUTPUT_ENABLE, autd::core::SEQ_BEGIN, autd::core::SEQ_END, autd::core::SEQ_GAIN_MODE, autd::core::SEQ_MODE, autd::core::WAIT_ON_SYNC, autd::core::Geometry::wavelength(), and autd::core::WRITE_BODY.
size()
size_t autd::core::PointSequence::size () const inline override virtual
Implements autd::core::Sequence.
Definition at line 138 of file sequence.hpp.
The documentation for this class was generated from the following file:
include/autd3/core/sequence.hpp