autd3: autd::Controller Class Reference
autd::Controller Class Reference
AUTD Controller.
#include <controller.hpp>
Classes
class STMController
Software spatio-temporal modulation controller.
class StreamCommaInputBody
class StreamCommaInputHeader
Public Member Functions
Controller () noexcept
~Controller () noexcept
Controller (const Controller &v) noexcept=delete
Controller & operator= (const Controller &obj)=delete
Controller (Controller &&obj)=default
Controller & operator= (Controller &&obj)=default
bool is_open () const
Verify the device is properly connected.
core::Geometry & geometry () noexcept
Geometry of the devices.
const core::Geometry & geometry () const noexcept
Geometry of the devices.
bool & output_enable () noexcept
Output enable.
bool output_enable () const noexcept
Output enable.
bool & silent_mode () noexcept
Silent mode.
bool silent_mode () const noexcept
Silent mode.
bool & reads_fpga_info () noexcept
If true, the devices return FPGA info in all frames. The FPGA info can be read by fpga_info().
bool reads_fpga_info () const noexcept
If true, the devices return FPGA info in all frames. The FPGA info can be read by fpga_info().
bool & force_fan () noexcept
If true, the fan will be forced to start.
bool force_fan () const noexcept
If true, the fan will be forced to start.
bool & output_balance () noexcept
If true, the applied voltage to transducers is dropped to GND while transducers are not being outputting.
bool output_balance () const noexcept
If true, the applied voltage to transducers is dropped to GND while transducers are not being outputting.
bool & check_ack () noexcept
If true, this controller check ack from devices.
bool check_ack () const noexcept
If true, this controller check ack from devices.
const std::vector< core::FPGAInfo > & fpga_info ()
FPGA info.
bool update_ctrl_flag ()
Update control flag.
void open (core::LinkPtr link)
Open device with a link.
bool clear ()
Clear all data in hardware.
bool close ()
Close the controller.
bool stop ()
Stop outputting.
bool pause ()
Pause outputting.
bool resume ()
Resume outputting.
template<class T >
std::enable_if_t< core::is_header_v< T >, bool > send (T &&header)
template<class T >
std::enable_if_t< core::is_body_v< T >, bool > send (T &&body)
template<class H , class B >
std::enable_if_t< std::conjunction_v< core::is_header< H >, core::is_body< B > >, bool > send (H &&header, B &&body)
template<class H , class B >
std::enable_if_t< std::conjunction_v< core::is_header< H >, core::is_body< B > >, bool > send (B &&body, H &&header)
std::vector< FirmwareInfo > firmware_info_list ()
Enumerate firmware information.
STMController stm ()
return pointer to software spatio-temporal modulation controller.
template<class T >
std::enable_if_t< core::is_header_v< T >, StreamCommaInputHeader > operator<< (T &&header)
template<class T >
std::enable_if_t< core::is_body_v< T >, StreamCommaInputBody > operator<< (T &&body)
Detailed Description
AUTD Controller.
Definition at line 31 of file controller.hpp.
Constructor & Destructor Documentation
Controller() [1/3]
autd::Controller::Controller () inline noexcept
Definition at line 59 of file controller.hpp.
~Controller()
autd::Controller::~Controller () noexcept
Controller() [2/3]
autd::Controller::Controller (const Controller & v) delete noexcept
Controller() [3/3]
autd::Controller::Controller (Controller && obj) default
Member Function Documentation
check_ack() [1/2]
bool autd::Controller::check_ack () const noexcept
If true, this controller check ack from devices.
check_ack() [2/2]
bool& autd::Controller::check_ack () noexcept
If true, this controller check ack from devices.
clear()
bool autd::Controller::clear ()
Clear all data in hardware.
Returns
if this function returns true and check_ack is true, it guarantees that the devices have processed the data.
close()
bool autd::Controller::close ()
Close the controller.
Returns
if this function returns true and check_ack is true, it guarantees that the devices have processed the data.
firmware_info_list()
std::vector<FirmwareInfo> autd::Controller::firmware_info_list ()
Enumerate firmware information.
Returns
firmware information list
force_fan() [1/2]
bool autd::Controller::force_fan () const noexcept
If true, the fan will be forced to start.
force_fan() [2/2]
bool& autd::Controller::force_fan () noexcept
If true, the fan will be forced to start.
fpga_info()
const std::vector<core::FPGAInfo>& autd::Controller::fpga_info ()
FPGA info.
Returns
ok with FPGA information if succeeded, or err with error message if failed
the first bit of FPGA info represents whether the fan is running.
geometry() [1/2]
const core::Geometry& autd::Controller::geometry () const noexcept
Geometry of the devices.
geometry() [2/2]
core::Geometry& autd::Controller::geometry () noexcept
Geometry of the devices.
is_open()
bool autd::Controller::is_open () const
Verify the device is properly connected.
open()
void autd::Controller::open (core::LinkPtr link)
Open device with a link.
Parameters
[in] link Link
operator<<() [1/2]
template<class T > std::enable_if_t<core::is_body_v<T>, StreamCommaInputBody> autd::Controller::operator<< (T && body) inline
Definition at line 345 of file controller.hpp.
operator<<() [2/2]
template<class T > std::enable_if_t<core::is_header_v<T>, StreamCommaInputHeader> autd::Controller::operator<< (T && header) inline
Definition at line 345 of file controller.hpp.
operator=() [1/2]
Controller& autd::Controller::operator= (const Controller & obj) delete
operator=() [2/2]
Controller& autd::Controller::operator= (Controller && obj) default
output_balance() [1/2]
bool autd::Controller::output_balance () const noexcept
If true, the applied voltage to transducers is dropped to GND while transducers are not being outputting.
output_balance() [2/2]
bool& autd::Controller::output_balance () noexcept
If true, the applied voltage to transducers is dropped to GND while transducers are not being outputting.
output_enable() [1/2]
bool autd::Controller::output_enable () const noexcept
Output enable.
output_enable() [2/2]
bool& autd::Controller::output_enable () noexcept
Output enable.
pause()
bool autd::Controller::pause ()
Pause outputting.
Returns
if this function returns true and check_ack is true, it guarantees that the devices have processed the data.
reads_fpga_info() [1/2]
bool autd::Controller::reads_fpga_info () const noexcept
If true, the devices return FPGA info in all frames. The FPGA info can be read by fpga_info().
reads_fpga_info() [2/2]
bool& autd::Controller::reads_fpga_info () noexcept
If true, the devices return FPGA info in all frames. The FPGA info can be read by fpga_info().
resume()
bool autd::Controller::resume ()
Resume outputting.
Returns
if this function returns true and check_ack is true, it guarantees that the devices have processed the data.
send() [1/4]
template<class H , class B > std::enable_if_t<std::conjunction_v<core::is_header<H>, core::is_body<B> >, bool> autd::Controller::send (B && body, H && header) inline
Definition at line 206 of file controller.hpp.
References autd::core::to_body(), and autd::core::to_header().
send() [2/4]
template<class H , class B > std::enable_if_t<std::conjunction_v<core::is_header<H>, core::is_body<B> >, bool> autd::Controller::send (H && header, B && body) inline
Definition at line 201 of file controller.hpp.
References autd::core::to_body(), and autd::core::to_header().
send() [3/4]
template<class T > std::enable_if_t<core::is_body_v<T>, bool> autd::Controller::send (T && body) inline
Definition at line 196 of file controller.hpp.
References autd::core::to_body().
send() [4/4]
template<class T > std::enable_if_t<core::is_header_v<T>, bool> autd::Controller::send (T && header) inline
Definition at line 191 of file controller.hpp.
References autd::core::to_header().
Referenced by autd::Controller::StreamCommaInputHeader::operator<<(), autd::Controller::StreamCommaInputBody::operator<<(), autd::Controller::StreamCommaInputBody::~StreamCommaInputBody(), and autd::Controller::StreamCommaInputHeader::~StreamCommaInputHeader().
silent_mode() [1/2]
bool autd::Controller::silent_mode () const noexcept
Silent mode.
silent_mode() [2/2]
bool& autd::Controller::silent_mode () noexcept
Silent mode.
stm()
STMController autd::Controller::stm ()
return pointer to software spatio-temporal modulation controller.
Never use Controller before calling STMController::finish
stop()
bool autd::Controller::stop ()
Stop outputting.
Returns
if this function returns true and check_ack is true, it guarantees that the devices have processed the data.
update_ctrl_flag()
bool autd::Controller::update_ctrl_flag ()
Update control flag.
Returns
if this function returns true and check_ack is true, it guarantees that the devices have processed the data.
The documentation for this class was generated from the following file:
include/autd3/controller.hpp