autd3: autd::core::Modulation Class Reference
autd::core::Modulation Class Reference abstract
Modulation controls the amplitude modulation.
#include <modulation.hpp>
Public Member Functions
Modulation () noexcept
Modulation (const size_t freq_div) noexcept
~Modulation () override=default
Modulation (const Modulation &v) noexcept=delete
Modulation & operator= (const Modulation &obj)=delete
Modulation (Modulation &&obj)=default
Modulation & operator= (Modulation &&obj)=default
virtual void calc ()=0
Calculate modulation data.
void build ()
Build modulation data.
void rebuild ()
Re-build modulation data.
const std::vector< uint8_t > & buffer () const
modulation data
size_t & sampling_freq_div_ratio () noexcept
sampling frequency division ratio
size_t sampling_freq_div_ratio () const noexcept
sampling frequency division ratio
double sampling_freq () const noexcept
modulation sampling frequency
void init () override
void pack (const uint8_t msg_id, TxDatagram &tx, const uint8_t fpga_ctrl_flag, const uint8_t cpu_ctrl_flag) override
bool is_finished () const override
Public Member Functions inherited from autd::core::IDatagramHeader
IDatagramHeader ()=default
virtual ~IDatagramHeader ()=default
IDatagramHeader (const IDatagramHeader &v) noexcept=delete
IDatagramHeader & operator= (const IDatagramHeader &obj)=delete
IDatagramHeader (IDatagramHeader &&obj)=default
IDatagramHeader & operator= (IDatagramHeader &&obj)=default
Detailed Description
Modulation controls the amplitude modulation.
Definition at line 25 of file modulation.hpp.
Constructor & Destructor Documentation
Modulation() [1/4]
autd::core::Modulation::Modulation () inline noexcept
Definition at line 27 of file modulation.hpp.
Modulation() [2/4]
autd::core::Modulation::Modulation (const size_t freq_div) inline explicit noexcept
Definition at line 28 of file modulation.hpp.
~Modulation()
autd::core::Modulation::~Modulation () override default
Modulation() [3/4]
autd::core::Modulation::Modulation (const Modulation & v) delete noexcept
Modulation() [4/4]
autd::core::Modulation::Modulation (Modulation && obj) default
Member Function Documentation
buffer()
const std::vector<uint8_t>& autd::core::Modulation::buffer () const inline
modulation data
Definition at line 63 of file modulation.hpp.
build()
void autd::core::Modulation::build () inline
Build modulation data.
Definition at line 43 of file modulation.hpp.
References calc(), autd::core::MOD_BUF_SIZE_MAX, and autd::core::MOD_SAMPLING_FREQ_DIV_MAX.
Referenced by init(), and rebuild().
calc()
virtual void autd::core::Modulation::calc () pure virtual
Calculate modulation data.
Implemented in autd::modulation::Square, autd::modulation::SineLegacy, autd::modulation::SineSquared, autd::modulation::Wav, autd::modulation::Sine, autd::modulation::RawPCM, autd::modulation::LPF, and autd::modulation::Static.
Referenced by build().
init()
void autd::core::Modulation::init () inline override virtual
Implements autd::core::IDatagramHeader.
Definition at line 84 of file modulation.hpp.
References build().
is_finished()
bool autd::core::Modulation::is_finished () const inline override virtual
Implements autd::core::IDatagramHeader.
Definition at line 117 of file modulation.hpp.
Referenced by pack().
operator=() [1/2]
Modulation& autd::core::Modulation::operator= (const Modulation & obj) delete
operator=() [2/2]
Modulation& autd::core::Modulation::operator= (Modulation && obj) default
pack()
void autd::core::Modulation::pack (const uint8_t msg_id, TxDatagram & tx, const uint8_t fpga_ctrl_flag, const uint8_t cpu_ctrl_flag) inline override virtual
Implements autd::core::IDatagramHeader.
Definition at line 89 of file modulation.hpp.
References autd::core::TxDatagram::data(), autd::core::FORCE_FAN, is_finished(), autd::core::MOD_BEGIN, autd::core::MOD_END, autd::core::MOD_FRAME_SIZE, autd::core::GlobalHeader::msg_id, autd::core::TxDatagram::num_bodies(), autd::core::OUTPUT_BALANCE, autd::core::READS_FPGA_INFO, sampling_freq_div_ratio(), and autd::core::SILENT.
rebuild()
void autd::core::Modulation::rebuild () inline
Re-build modulation data.
Definition at line 55 of file modulation.hpp.
References build().
sampling_freq()
double autd::core::Modulation::sampling_freq () const inline noexcept
modulation sampling frequency
Definition at line 82 of file modulation.hpp.
References autd::core::MOD_SAMPLING_FREQ_BASE.
sampling_freq_div_ratio() [1/2]
size_t autd::core::Modulation::sampling_freq_div_ratio () const inline noexcept
sampling frequency division ratio
sampling frequency will be autd::core::MOD_SAMPLING_FREQ_BASE /(sampling frequency division ratio). The value must be in 1, 2, ..., autd::core::MOD_SAMPLING_FREQ_DIV_MAX.
Definition at line 77 of file modulation.hpp.
sampling_freq_div_ratio() [2/2]
size_t& autd::core::Modulation::sampling_freq_div_ratio () inline noexcept
sampling frequency division ratio
sampling frequency will be autd::core::MOD_SAMPLING_FREQ_BASE /(sampling frequency division ratio). The value must be in 1, 2, ..., autd::core::MOD_SAMPLING_FREQ_DIV_MAX.
Definition at line 70 of file modulation.hpp.
Referenced by pack().
The documentation for this class was generated from the following file:
include/autd3/core/modulation.hpp