autd3: autd::core::Gain Class Reference
autd::core::Gain Class Reference abstract
Gain controls the duty ratio and phase of each transducer in AUTD devices.
#include <gain.hpp>
Public Member Functions
virtual void calc (const Geometry &geometry)=0
Calculate duty ratio and phase of each transducer.
void build (const Geometry &geometry)
Initialize data and call calc().
void rebuild (const Geometry &geometry)
Re-calculate duty ratio and phase of each transducer.
const std::vector< Drive > & data () const
Getter function for the data of duty ratio and phase of each transducers.
void init () override
void pack (const Geometry &geometry, TxDatagram &tx) override
bool is_finished () const override
Gain () noexcept
~Gain () override=default
Gain (const Gain &v) noexcept=delete
Gain & operator= (const Gain &obj)=delete
Gain (Gain &&obj)=default
Gain & operator= (Gain &&obj)=default
Public Member Functions inherited from autd::core::datagram::IDatagramBody
IDatagramBody ()=default
virtual ~IDatagramBody ()=default
IDatagramBody (const IDatagramBody &v) noexcept=delete
IDatagramBody & operator= (const IDatagramBody &obj)=delete
IDatagramBody (IDatagramBody &&obj)=default
IDatagramBody & operator= (IDatagramBody &&obj)=default
Detailed Description
Gain controls the duty ratio and phase of each transducer in AUTD devices.
Definition at line 26 of file gain.hpp.
Constructor & Destructor Documentation
Gain() [1/3]
autd::core::Gain::Gain () inline noexcept
Definition at line 78 of file gain.hpp.
~Gain()
autd::core::Gain::~Gain () override default
Gain() [2/3]
autd::core::Gain::Gain (const Gain & v) delete noexcept
Gain() [3/3]
autd::core::Gain::Gain (Gain && obj) default
Member Function Documentation
build()
void autd::core::Gain::build (const Geometry & geometry) inline
Initialize data and call calc().
Parameters
geometry Geometry
Definition at line 38 of file gain.hpp.
References calc(), and autd::core::Geometry::num_transducers().
Referenced by autd::gain::Grouped::add(), autd::core::GainSequence::add(), pack(), and rebuild().
calc()
virtual void autd::core::Gain::calc (const Geometry & geometry) pure virtual
Calculate duty ratio and phase of each transducer.
Parameters
geometry Geometry
Implemented in autd::gain::holo::Greedy, autd::gain::holo::APO, autd::gain::holo::GradientDescent, autd::gain::holo::GaussNewton, autd::gain::TransducerTest, autd::gain::holo::LM, autd::gain::BesselBeam, autd::gain::holo::GSPAT, autd::gain::holo::GS, autd::gain::FocalPoint, autd::gain::holo::Naive, autd::gain::PlaneWave, autd::gain::holo::EVD, autd::gain::holo::SDP, autd::gain::Grouped, and autd::gain::Null.
Referenced by build().
data()
const std::vector<Drive>& autd::core::Gain::data () const inline
Getter function for the data of duty ratio and phase of each transducers.
Definition at line 60 of file gain.hpp.
Referenced by autd::gain::Grouped::add(), and autd::core::GainSequence::add().
init()
void autd::core::Gain::init () inline override virtual
Implements autd::core::datagram::IDatagramBody.
Definition at line 62 of file gain.hpp.
is_finished()
bool autd::core::Gain::is_finished () const inline override virtual
Implements autd::core::datagram::IDatagramBody.
Definition at line 76 of file gain.hpp.
operator=() [1/2]
Gain& autd::core::Gain::operator= (const Gain & obj) delete
operator=() [2/2]
Gain& autd::core::Gain::operator= (Gain && obj) default
pack()
void autd::core::Gain::pack (const Geometry & geometry, TxDatagram & tx) inline override virtual
Implements autd::core::datagram::IDatagramBody.
Definition at line 64 of file gain.hpp.
References autd::core::TxDatagram::body(), build(), autd::core::GlobalHeader::fpga_ctrl_flags, autd::core::TxDatagram::header(), autd::core::TxDatagram::num_bodies(), autd::core::Geometry::num_devices(), autd::core::OUTPUT_ENABLE, autd::core::SEQ_MODE, and autd::core::WRITE_BODY.
rebuild()
void autd::core::Gain::rebuild (const Geometry & geometry) inline
Re-calculate duty ratio and phase of each transducer.
Parameters
geometry Geometry
Definition at line 52 of file gain.hpp.
References build().
The documentation for this class was generated from the following file:
include/autd3/core/gain.hpp