autd3: autd::Controller::STMController Class Reference
autd::Controller::STMController Class Reference
Software spatio-temporal modulation controller.
#include <controller.hpp>
Classes
class StreamCommaInputSTM
Public Member Functions
void add (core::Gain &gain) const
Add gain for STM.
void start (double freq)
Start Spatio-Temporal Modulation.
void stop ()
Suspend Spatio-Temporal Modulation.
void finish ()
Finish Spatio-Temporal Modulation.
template<class T >
std::enable_if_t< core::type_traits::is_gain_v< T >, StreamCommaInputSTM > operator<< (T &&gain)
~STMController ()
STMController (const STMController &v) noexcept=delete
STMController & operator= (const STMController &obj)=delete
STMController (STMController &&obj)=default
STMController & operator= (STMController &&obj)=default
Friends
class Controller
Detailed Description
Software spatio-temporal modulation controller.
Definition at line 230 of file controller.hpp.
Constructor & Destructor Documentation
~STMController()
autd::Controller::STMController::~STMController () inline
Definition at line 293 of file controller.hpp.
References finish().
STMController() [1/2]
autd::Controller::STMController::STMController (const STMController & v) delete noexcept
STMController() [2/2]
autd::Controller::STMController::STMController (STMController && obj) default
Member Function Documentation
add()
void autd::Controller::STMController::add (core::Gain & gain) const
Add gain for STM.
Referenced by autd::Controller::STMController::StreamCommaInputSTM::operator,(), and autd::Controller::STMController::StreamCommaInputSTM::operator=().
finish()
void autd::Controller::STMController::finish ()
Finish Spatio-Temporal Modulation.
Added gains will be removed. Never use this STMController after calling this function.
Referenced by ~STMController().
operator<<()
template<class T > std::enable_if_t<core::type_traits::is_gain_v<T>, StreamCommaInputSTM> autd::Controller::STMController::operator<< (T && gain) inline
Definition at line 258 of file controller.hpp.
operator=() [1/2]
STMController& autd::Controller::STMController::operator= (const STMController & obj) delete
operator=() [2/2]
STMController& autd::Controller::STMController::operator= (STMController && obj) default
start()
void autd::Controller::STMController::start (double freq)
Start Spatio-Temporal Modulation.
Parameters
[in] freq Frequency of STM modulation
Generate STM modulation by switching gains appended by add_gain() at the freq. The accuracy depends on the computer, for example, about 1ms on Windows. Note that it is affected by interruptions, and so on.
stop()
void autd::Controller::STMController::stop ()
Suspend Spatio-Temporal Modulation.
Friends And Related Function Documentation
Controller
friend class Controller friend
Definition at line 232 of file controller.hpp.
The documentation for this class was generated from the following file:
include/autd3/controller.hpp