autd3: autd::core::Geometry Class Reference
autd::core::Geometry Class Reference
Geometry of all devices.
#include <geometry.hpp>
Public Member Functions
Geometry ()
~Geometry ()=default
Geometry (const Geometry &v) noexcept=default
Geometry & operator= (const Geometry &obj)=default
Geometry (Geometry &&obj)=default
Geometry & operator= (Geometry &&obj)=default
size_t add_device (const Vector3 &position, const Vector3 &euler_angles, const size_t group=0)
Add new device with position and rotation. Note that the transform is done with order: Translate -> Rotate.
size_t add_device (const Vector3 &position, const Quaternion &quaternion, const size_t group=0)
Same as add_device(const Vector3&, const Vector3&, const size_t), but using quaternion rather than zyz euler angles.
size_t del_device (const size_t idx)
Delete device.
void clear_devices ()
Clear all devices.
double & wavelength () noexcept
ultrasound wavelength
double & attenuation_coefficient () noexcept
attenuation coefficient
size_t num_devices () const noexcept
Number of devices.
size_t num_transducers () const noexcept
Number of transducers.
size_t group_id_for_device_idx (const size_t device_idx) const
Convert device ID into group ID.
const Vector3 & position (const size_t global_transducer_idx) const
Position of a transducer specified by id.
const Vector3 & position (const size_t device_idx, const size_t local_transducer_idx) const
Position of a transducer specified by id.
Vector3 to_local_position (const size_t device_idx, const Vector3 &global_position) const
Convert a global position to a local position.
const Vector3 & direction (const size_t device_idx) const
Normalized direction of a device.
const Vector3 & x_direction (const size_t device_idx) const
Normalized long-axis direction of a device.
const Vector3 & y_direction (const size_t device_idx) const
Normalized short-axis direction of a device.
const Vector3 & z_direction (const size_t device_idx) const
Same as the direction()
Static Public Member Functions
static size_t device_idx_for_trans_idx (const size_t transducer_idx)
Convert transducer index into device index.
Detailed Description
Geometry of all devices.
Definition at line 83 of file geometry.hpp.
Constructor & Destructor Documentation
Geometry() [1/3]
autd::core::Geometry::Geometry () inline
Definition at line 85 of file geometry.hpp.
~Geometry()
autd::core::Geometry::~Geometry () default
Geometry() [2/3]
autd::core::Geometry::Geometry (const Geometry & v) default noexcept
Geometry() [3/3]
autd::core::Geometry::Geometry (Geometry && obj) default
Member Function Documentation
add_device() [1/2]
size_t autd::core::Geometry::add_device (const Vector3 & position, const Quaternion & quaternion, const size_t group = 0) inline
Same as add_device(const Vector3&, const Vector3&, const size_t), but using quaternion rather than zyz euler angles.
Parameters
position Position of transducer #0, which is the one at the lower-left corner.
quaternion rotation quaternion of the device.
group Grouping ID
Returns
an id of added device
Definition at line 114 of file geometry.hpp.
References position().
add_device() [2/2]
size_t autd::core::Geometry::add_device (const Vector3 & position, const Vector3 & euler_angles, const size_t group = 0) inline
Add new device with position and rotation. Note that the transform is done with order: Translate -> Rotate.
Parameters
position Position of transducer #0, which is the one at the lower-left corner. (The lower-left corner is the one with the two missing transducers.)
euler_angles ZYZ convention euler angle of the device
group Grouping ID of the device
Returns
an id of added device
Definition at line 100 of file geometry.hpp.
References position().
attenuation_coefficient()
double& autd::core::Geometry::attenuation_coefficient () inline noexcept
attenuation coefficient
Definition at line 144 of file geometry.hpp.
clear_devices()
void autd::core::Geometry::clear_devices () inline
Clear all devices.
Definition at line 134 of file geometry.hpp.
del_device()
size_t autd::core::Geometry::del_device (const size_t idx) inline
Delete device.
Parameters
idx Index of the device to delete
Returns
an index of deleted device
Definition at line 126 of file geometry.hpp.
device_idx_for_trans_idx()
static size_t autd::core::Geometry::device_idx_for_trans_idx (const size_t transducer_idx) inline static
Convert transducer index into device index.
Definition at line 208 of file geometry.hpp.
References autd::core::NUM_TRANS_IN_UNIT.
Referenced by position().
direction()
const Vector3& autd::core::Geometry::direction (const size_t device_idx) const inline
Normalized direction of a device.
Definition at line 188 of file geometry.hpp.
group_id_for_device_idx()
size_t autd::core::Geometry::group_id_for_device_idx (const size_t device_idx) const inline
Convert device ID into group ID.
Definition at line 159 of file geometry.hpp.
num_devices()
size_t autd::core::Geometry::num_devices () const inline noexcept
Number of devices.
Definition at line 149 of file geometry.hpp.
Referenced by num_transducers().
num_transducers()
size_t autd::core::Geometry::num_transducers () const inline noexcept
Number of transducers.
Definition at line 154 of file geometry.hpp.
References num_devices(), and autd::core::NUM_TRANS_IN_UNIT.
operator=() [1/2]
Geometry& autd::core::Geometry::operator= (const Geometry & obj) default
operator=() [2/2]
Geometry& autd::core::Geometry::operator= (Geometry && obj) default
position() [1/2]
const Vector3& autd::core::Geometry::position (const size_t device_idx, const size_t local_transducer_idx) const inline
Position of a transducer specified by id.
Definition at line 172 of file geometry.hpp.
position() [2/2]
const Vector3& autd::core::Geometry::position (const size_t global_transducer_idx) const inline
Position of a transducer specified by id.
Definition at line 164 of file geometry.hpp.
References device_idx_for_trans_idx(), and autd::core::NUM_TRANS_IN_UNIT.
Referenced by add_device().
to_local_position()
Vector3 autd::core::Geometry::to_local_position (const size_t device_idx, const Vector3 & global_position) const inline
Convert a global position to a local position.
Definition at line 179 of file geometry.hpp.
wavelength()
double& autd::core::Geometry::wavelength () inline noexcept
ultrasound wavelength
Definition at line 139 of file geometry.hpp.
x_direction()
const Vector3& autd::core::Geometry::x_direction (const size_t device_idx) const inline
Normalized long-axis direction of a device.
Definition at line 193 of file geometry.hpp.
y_direction()
const Vector3& autd::core::Geometry::y_direction (const size_t device_idx) const inline
Normalized short-axis direction of a device.
Definition at line 198 of file geometry.hpp.
z_direction()
const Vector3& autd::core::Geometry::z_direction (const size_t device_idx) const inline
Same as the direction()
Definition at line 203 of file geometry.hpp.
The documentation for this class was generated from the following file:
include/autd3/core/geometry.hpp