autd3: autd::core::DelayOffsets Class Reference
autd::core::DelayOffsets Class Reference final
DelayOffsets controls the duty offset and delay of each transducer in AUTD devices.
#include <delay_offset.hpp>
Public Member Functions
DelayOffset & operator[] (const size_t i)
const DelayOffset & operator[] (const size_t i) const
void init () override
void pack (const Geometry &geometry, TxDatagram &tx) override
bool is_finished () const override
DelayOffsets (const size_t num_devices)
~DelayOffsets () override=default
DelayOffsets (const DelayOffsets &v) noexcept=delete
DelayOffsets & operator= (const DelayOffsets &obj)=delete
DelayOffsets (DelayOffsets &&obj)=default
DelayOffsets & operator= (DelayOffsets &&obj)=default
Public Member Functions inherited from autd::core::datagram::IDatagramBody
IDatagramBody ()=default
virtual ~IDatagramBody ()=default
IDatagramBody (const IDatagramBody &v) noexcept=delete
IDatagramBody & operator= (const IDatagramBody &obj)=delete
IDatagramBody (IDatagramBody &&obj)=default
IDatagramBody & operator= (IDatagramBody &&obj)=default
Detailed Description
DelayOffsets controls the duty offset and delay of each transducer in AUTD devices.
Definition at line 23 of file delay_offset.hpp.
Constructor & Destructor Documentation
DelayOffsets() [1/3]
autd::core::DelayOffsets::DelayOffsets (const size_t num_devices) inline explicit
Definition at line 40 of file delay_offset.hpp.
~DelayOffsets()
autd::core::DelayOffsets::~DelayOffsets () override default
DelayOffsets() [2/3]
autd::core::DelayOffsets::DelayOffsets (const DelayOffsets & v) delete noexcept
DelayOffsets() [3/3]
autd::core::DelayOffsets::DelayOffsets (DelayOffsets && obj) default
Member Function Documentation
init()
void autd::core::DelayOffsets::init () inline override virtual
Implements autd::core::datagram::IDatagramBody.
Definition at line 28 of file delay_offset.hpp.
is_finished()
bool autd::core::DelayOffsets::is_finished () const inline override virtual
Implements autd::core::datagram::IDatagramBody.
Definition at line 38 of file delay_offset.hpp.
operator=() [1/2]
DelayOffsets& autd::core::DelayOffsets::operator= (const DelayOffsets & obj) delete
operator=() [2/2]
DelayOffsets& autd::core::DelayOffsets::operator= (DelayOffsets && obj) default
operator[]() [1/2]
DelayOffset& autd::core::DelayOffsets::operator[] (const size_t i) inline
Definition at line 25 of file delay_offset.hpp.
operator[]() [2/2]
const DelayOffset& autd::core::DelayOffsets::operator[] (const size_t i) const inline
Definition at line 26 of file delay_offset.hpp.
pack()
void autd::core::DelayOffsets::pack (const Geometry & geometry, TxDatagram & tx) inline override virtual
Implements autd::core::datagram::IDatagramBody.
Definition at line 30 of file delay_offset.hpp.
References autd::core::TxDatagram::body(), autd::core::GlobalHeader::cpu_ctrl_flags, autd::core::DELAY_OFFSET, autd::core::TxDatagram::header(), autd::core::TxDatagram::num_bodies(), autd::core::Geometry::num_devices(), and autd::core::WRITE_BODY.
The documentation for this class was generated from the following file:
include/autd3/core/delay_offset.hpp