autd3: autd::gain::Grouped Class Reference
autd::gain::Grouped Class Reference final
Gain to group some gains.
#include <primitive.hpp>
Public Member Functions
template<class T >
std::enable_if_t< core::is_gain_v< T > > add (const size_t device_id, T &&gain)
Decide which device outputs which Gain.
void calc (const core::Geometry &geometry) override
Calculate duty ratio and phase of each transducer.
Grouped (const core::Geometry &geometry)
~Grouped () override=default
Grouped (const Grouped &v) noexcept=delete
Grouped & operator= (const Grouped &obj)=delete
Grouped (Grouped &&obj)=default
Grouped & operator= (Grouped &&obj)=delete
Public Member Functions inherited from autd::core::Gain
void build (const Geometry &geometry)
Initialize data and call calc().
void rebuild (const Geometry &geometry)
Re-calculate duty ratio and phase of each transducer.
const std::vector< Drive > & data () const
Getter function for the data of duty ratio and phase of each transducers.
void init () override
void pack (const Geometry &geometry, TxDatagram &tx) override
bool is_finished () const override
Gain () noexcept
~Gain () override=default
Gain (const Gain &v) noexcept=delete
Gain & operator= (const Gain &obj)=delete
Gain (Gain &&obj)=default
Gain & operator= (Gain &&obj)=default
Public Member Functions inherited from autd::core::IDatagramBody
IDatagramBody ()=default
virtual ~IDatagramBody ()=default
IDatagramBody (const IDatagramBody &v) noexcept=delete
IDatagramBody & operator= (const IDatagramBody &obj)=delete
IDatagramBody (IDatagramBody &&obj)=default
IDatagramBody & operator= (IDatagramBody &&obj)=default
Detailed Description
Gain to group some gains.
Definition at line 48 of file primitive.hpp.
Constructor & Destructor Documentation
Grouped() [1/3]
autd::gain::Grouped::Grouped (const core::Geometry & geometry) inline explicit
Definition at line 70 of file primitive.hpp.
References autd::core::Geometry::num_transducers().
~Grouped()
autd::gain::Grouped::~Grouped () override default
Grouped() [2/3]
autd::gain::Grouped::Grouped (const Grouped & v) delete noexcept
Grouped() [3/3]
autd::gain::Grouped::Grouped (Grouped && obj) default
Member Function Documentation
add()
template<class T > std::enable_if_t<core::is_gain_v<T> > autd::gain::Grouped::add (const size_t device_id, T && gain) inline
Decide which device outputs which Gain.
Parameters
device_id device id
gain gain
Definition at line 56 of file primitive.hpp.
References autd::core::Gain::build(), autd::core::Gain::data(), autd::core::Geometry::num_devices(), autd::core::NUM_TRANS_IN_UNIT, and autd::core::to_gain().
calc()
void autd::gain::Grouped::calc (const core::Geometry & geometry) inline override virtual
Calculate duty ratio and phase of each transducer.
Parameters
geometry Geometry
Implements autd::core::Gain.
Definition at line 66 of file primitive.hpp.
operator=() [1/2]
Grouped& autd::gain::Grouped::operator= (const Grouped & obj) delete
operator=() [2/2]
Grouped& autd::gain::Grouped::operator= (Grouped && obj) delete
The documentation for this class was generated from the following file:
include/autd3/gain/primitive.hpp