autd3: autd::core::GainSequence Class Reference
autd::core::GainSequence Class Reference final
GainSequence provides a function to display Gain sequentially and periodically.
#include <sequence.hpp>
Classes
class StreamCommaInputGS
Public Member Functions
GainSequence (const Geometry &geometry) noexcept
GainSequence (const Geometry &geometry, const GAIN_MODE gain_mode) noexcept
size_t size () const override
template<class T >
std::enable_if_t< type_traits::is_gain_v< T > > add (T &&gain)
Add gain.
GAIN_MODE & gain_mode ()
GAIN_MODE gain_mode () const
void init () override
void pack (const Geometry &geometry, TxDatagram &tx) override
bool is_finished () const override
template<class T >
std::enable_if_t< type_traits::is_gain_v< T >, StreamCommaInputGS > operator<< (T &&gain)
Public Member Functions inherited from autd::core::Sequence
Sequence ()
~Sequence () override=default
Sequence (const Sequence &v) noexcept=delete
Sequence & operator= (const Sequence &obj)=delete
Sequence (Sequence &&obj)=default
Sequence & operator= (Sequence &&obj)=default
double set_frequency (const double freq)
Set frequency of the sequence.
double frequency () const
size_t period_us () const
double sampling_freq () const
size_t sampling_period_us () const noexcept
size_t & sampling_freq_div_ratio () noexcept
size_t sampling_freq_div_ratio () const noexcept
bool wait_on_sync () const noexcept
If true, the output will be start after synchronization.
bool & wait_on_sync () noexcept
If true, the output will be start after synchronization.
Public Member Functions inherited from autd::core::datagram::IDatagramBody
IDatagramBody ()=default
virtual ~IDatagramBody ()=default
IDatagramBody (const IDatagramBody &v) noexcept=delete
IDatagramBody & operator= (const IDatagramBody &obj)=delete
IDatagramBody (IDatagramBody &&obj)=default
IDatagramBody & operator= (IDatagramBody &&obj)=default
Detailed Description
GainSequence provides a function to display Gain sequentially and periodically.
GainSequence uses a timer on the FPGA to ensure that Gain is precisely timed. GainSequence currently has the following three limitations.
The maximum number of gains is autd::core::GAIN_SEQ_BUFFER_SIZE_MAX.
The sampling interval of gains is an integer multiple of 25us and less than 25us x autd::core::SEQ_SAMPLING_FREQ_DIV_MAX.
Definition at line 273 of file sequence.hpp.
Constructor & Destructor Documentation
GainSequence() [1/2]
autd::core::GainSequence::GainSequence (const Geometry & geometry) inline explicit noexcept
Definition at line 298 of file sequence.hpp.
GainSequence() [2/2]
autd::core::GainSequence::GainSequence (const Geometry & geometry, const GAIN_MODE gain_mode) inline explicit noexcept
Definition at line 299 of file sequence.hpp.
Member Function Documentation
add()
template<class T > std::enable_if_t<type_traits::is_gain_v<T> > autd::core::GainSequence::add (T && gain) inline
Add gain.
Parameters
[in] gain gain
Definition at line 309 of file sequence.hpp.
References autd::core::Gain::build(), autd::core::Gain::data(), autd::core::GAIN_SEQ_BUFFER_SIZE_MAX, and autd::core::type_traits::to_gain().
Referenced by autd::core::GainSequence::StreamCommaInputGS::operator<<().
gain_mode() [1/2]
GAIN_MODE& autd::core::GainSequence::gain_mode () inline
Returns
GAIN_MODE
Definition at line 324 of file sequence.hpp.
gain_mode() [2/2]
GAIN_MODE autd::core::GainSequence::gain_mode () const inline
Returns
GAIN_MODE
Definition at line 328 of file sequence.hpp.
init()
void autd::core::GainSequence::init () inline override virtual
Implements autd::core::datagram::IDatagramBody.
Definition at line 330 of file sequence.hpp.
is_finished()
bool autd::core::GainSequence::is_finished () const inline override virtual
Implements autd::core::datagram::IDatagramBody.
Definition at line 388 of file sequence.hpp.
Referenced by pack().
operator<<()
template<class T > std::enable_if_t<type_traits::is_gain_v<T>, StreamCommaInputGS> autd::core::GainSequence::operator<< (T && gain) inline
Definition at line 388 of file sequence.hpp.
pack()
void autd::core::GainSequence::pack (const Geometry & geometry, TxDatagram & tx) inline override virtual
Implements autd::core::datagram::IDatagramBody.
Definition at line 332 of file sequence.hpp.
References autd::core::TxDatagram::body(), autd::core::GlobalHeader::cpu_ctrl_flags, autd::core::DUTY_PHASE_FULL, autd::core::TxDatagram::header(), is_finished(), autd::core::TxDatagram::num_bodies(), autd::core::Geometry::num_devices(), autd::core::OUTPUT_ENABLE, autd::core::PHASE_FULL, autd::core::PHASE_HALF, autd::core::SEQ_BEGIN, autd::core::SEQ_END, autd::core::SEQ_GAIN_MODE, autd::core::SEQ_MODE, size(), autd::core::WAIT_ON_SYNC, and autd::core::WRITE_BODY.
size()
size_t autd::core::GainSequence::size () const inline override virtual
Implements autd::core::Sequence.
Definition at line 302 of file sequence.hpp.
Referenced by pack().
The documentation for this class was generated from the following file:
include/autd3/core/sequence.hpp