autd3: autd::core::Sequence Class Reference
autd::core::Sequence Class Reference abstract
Sequence provide hardware Spatio-Temporal Modulation or Lateral Modulation function.
#include <sequence.hpp>
Public Member Functions
Sequence ()
~Sequence () override=default
Sequence (const Sequence &v) noexcept=delete
Sequence & operator= (const Sequence &obj)=delete
Sequence (Sequence &&obj)=default
Sequence & operator= (Sequence &&obj)=default
virtual size_t size () const =0
double set_frequency (const double freq)
Set frequency of the sequence.
double frequency () const
size_t period_us () const
double sampling_freq () const
size_t sampling_period_us () const noexcept
size_t & sampling_freq_div_ratio () noexcept
size_t sampling_freq_div_ratio () const noexcept
bool wait_on_sync () const noexcept
If true, the output will be start after synchronization.
bool & wait_on_sync () noexcept
If true, the output will be start after synchronization.
Public Member Functions inherited from autd::core::datagram::IDatagramBody
IDatagramBody ()=default
virtual ~IDatagramBody ()=default
IDatagramBody (const IDatagramBody &v) noexcept=delete
IDatagramBody & operator= (const IDatagramBody &obj)=delete
IDatagramBody (IDatagramBody &&obj)=default
IDatagramBody & operator= (IDatagramBody &&obj)=default
virtual void init ()=0
virtual void pack (const Geometry &geometry, TxDatagram &tx)=0
virtual bool is_finished () const =0
Detailed Description
Sequence provide hardware Spatio-Temporal Modulation or Lateral Modulation function.
Definition at line 28 of file sequence.hpp.
Constructor & Destructor Documentation
Sequence() [1/3]
autd::core::Sequence::Sequence () inline
Definition at line 30 of file sequence.hpp.
~Sequence()
autd::core::Sequence::~Sequence () override default
Sequence() [2/3]
autd::core::Sequence::Sequence (const Sequence & v) delete noexcept
Sequence() [3/3]
autd::core::Sequence::Sequence (Sequence && obj) default
Member Function Documentation
frequency()
double autd::core::Sequence::frequency () const inline
Returns
frequency of sequence
Definition at line 55 of file sequence.hpp.
References sampling_freq(), and size().
Referenced by set_frequency().
operator=() [1/2]
Sequence& autd::core::Sequence::operator= (const Sequence & obj) delete
operator=() [2/2]
Sequence& autd::core::Sequence::operator= (Sequence && obj) default
period_us()
size_t autd::core::Sequence::period_us () const inline
Returns
period of sequence in micro seconds
Definition at line 60 of file sequence.hpp.
References sampling_period_us(), and size().
sampling_freq()
double autd::core::Sequence::sampling_freq () const inline
The sampling period is limited to an integer multiple of 25us. Therefore, the sampling frequency must be 40kHz/N, where N=1, 2, ..., autd::core::SEQ_SAMPLING_FREQ_DIV_MAX.
Returns
double Sampling frequency of sequence
Definition at line 67 of file sequence.hpp.
References autd::core::SEQ_BASE_FREQ.
Referenced by frequency().
sampling_freq_div_ratio() [1/2]
size_t autd::core::Sequence::sampling_freq_div_ratio () const inline noexcept
The sampling frequency division ratio means the autd::core::SEQ_BASE_FREQ/(sampling frequency) = (sampling period)/25us.
Returns
size_t Sampling frequency division ratio
The value must be in 1, 2, ..., autd::core::SEQ_SAMPLING_FREQ_DIV_MAX.
Definition at line 86 of file sequence.hpp.
sampling_freq_div_ratio() [2/2]
size_t& autd::core::Sequence::sampling_freq_div_ratio () inline noexcept
The sampling frequency division ratio means the autd::core::SEQ_BASE_FREQ/(sampling frequency) = (sampling period)/25us.
Returns
size_t Sampling frequency division ratio
The value must be in 1, 2, ..., autd::core::SEQ_SAMPLING_FREQ_DIV_MAX.
Definition at line 79 of file sequence.hpp.
sampling_period_us()
size_t autd::core::Sequence::sampling_period_us () const inline noexcept
Returns
sampling period of sequence in micro seconds
Definition at line 72 of file sequence.hpp.
References autd::core::SEQ_BASE_FREQ.
Referenced by period_us().
set_frequency()
double autd::core::Sequence::set_frequency (const double freq) inline
Set frequency of the sequence.
Parameters
[in] freq Frequency of the sequence
Sequence mode has some constraints, which determine the actual frequency of the sequence.
Returns
double Actual frequency of sequence
Definition at line 45 of file sequence.hpp.
References frequency(), autd::core::SEQ_BASE_FREQ, autd::core::SEQ_SAMPLING_FREQ_DIV_MAX, and size().
size()
virtual size_t autd::core::Sequence::size () const pure virtual
Implemented in autd::core::GainSequence, and autd::core::PointSequence.
Referenced by frequency(), period_us(), and set_frequency().
wait_on_sync() [1/2]
bool autd::core::Sequence::wait_on_sync () const inline noexcept
If true, the output will be start after synchronization.
Definition at line 91 of file sequence.hpp.
wait_on_sync() [2/2]
bool& autd::core::Sequence::wait_on_sync () inline noexcept
If true, the output will be start after synchronization.
Definition at line 96 of file sequence.hpp.
The documentation for this class was generated from the following file:
include/autd3/core/sequence.hpp