autd3: autd::Controller::STMController::StreamCommaInputSTM Class Reference
autd::Controller::STMController::StreamCommaInputSTM Class Reference
#include <controller.hpp>
Public Member Functions
StreamCommaInputSTM (STMController &cnt)
~StreamCommaInputSTM ()=default
StreamCommaInputSTM (const StreamCommaInputSTM &v) noexcept=delete
StreamCommaInputSTM & operator= (const StreamCommaInputSTM &obj)=delete
StreamCommaInputSTM (StreamCommaInputSTM &&obj)=default
StreamCommaInputSTM & operator= (StreamCommaInputSTM &&obj)=delete
template<class T >
std::enable_if_t< core::type_traits::is_gain_v< T >, StreamCommaInputSTM & > operator<< (T &&gain)
template<class T >
std::enable_if_t< core::type_traits::is_gain_v< T >, StreamCommaInputSTM & > operator, (T &&gain)
Friends
class Controller
Detailed Description
Definition at line 260 of file controller.hpp.
Constructor & Destructor Documentation
StreamCommaInputSTM() [1/3]
autd::Controller::STMController::StreamCommaInputSTM::StreamCommaInputSTM (STMController & cnt) inline explicit
Definition at line 264 of file controller.hpp.
~StreamCommaInputSTM()
autd::Controller::STMController::StreamCommaInputSTM::~StreamCommaInputSTM () default
StreamCommaInputSTM() [2/3]
autd::Controller::STMController::StreamCommaInputSTM::StreamCommaInputSTM (const StreamCommaInputSTM & v) delete noexcept
StreamCommaInputSTM() [3/3]
autd::Controller::STMController::StreamCommaInputSTM::StreamCommaInputSTM (StreamCommaInputSTM && obj) default
Member Function Documentation
operator,()
template<class T > std::enable_if_t<core::type_traits::is_gain_v<T>, StreamCommaInputSTM&> autd::Controller::STMController::StreamCommaInputSTM::operator, (T && gain) inline
Definition at line 278 of file controller.hpp.
References autd::Controller::STMController::add(), and autd::core::type_traits::to_gain().
operator<<()
template<class T > std::enable_if_t<core::type_traits::is_gain_v<T>, StreamCommaInputSTM&> autd::Controller::STMController::StreamCommaInputSTM::operator<< (T && gain) inline
Definition at line 269 of file controller.hpp.
operator=() [1/2]
StreamCommaInputSTM& autd::Controller::STMController::StreamCommaInputSTM::operator= (const StreamCommaInputSTM & obj) delete
operator=() [2/2]
StreamCommaInputSTM& autd::Controller::STMController::StreamCommaInputSTM::operator= (StreamCommaInputSTM && obj) delete
References autd::Controller::STMController::add(), and autd::core::type_traits::to_gain().
Friends And Related Function Documentation
Controller
friend class Controller friend
Definition at line 261 of file controller.hpp.
The documentation for this class was generated from the following file:
include/autd3/controller.hpp