autd3: autd::core::type_traits Namespace Reference
autd::core::type_traits Namespace Reference
Classes
struct is_body
Checks if a type is IDatagramBody.
struct is_body_ptr
Checks if a type is pointer of IDatagramBody.
struct is_body_ref
Checks if a type is reference of IDatagramBody.
struct is_gain
Checks if a type is Gain.
struct is_gain_ptr
Checks if a type is pointer of Gain.
struct is_gain_ref
Checks if a type is reference of Gain.
struct is_header
Checks if a type is IDatagramHeader.
struct is_header_ptr
Checks if a type is pointer of IDatagramHeader.
struct is_header_ref
Checks if a type is reference of IDatagramHeader.
struct is_pointer_of
Checks if a type is pointer.
struct is_raw_pointer_of
Checks if a type is raw pointer.
struct is_smart_pointer_of
Checks if a type is smart pointer.
Functions
template<class T >
std::enable_if_t< is_header_v< T >, datagram::IDatagramHeader & > to_header (T &&header)
template<class T >
std::enable_if_t< is_body_v< T >, datagram::IDatagramBody & > to_body (T &&body)
template<class T >
std::enable_if_t< is_gain_v< T >, Gain & > to_gain (T &&gain)
Variables
template<typename T >
constexpr bool is_body_ref_v = is_body_ref<T>::value
template<typename T >
constexpr bool is_body_ptr_v = is_body_ptr<T>::value
template<typename T >
constexpr bool is_body_v = is_body<T>::value
template<typename T >
constexpr bool is_header_ref_v = is_header_ref<T>::value
template<typename T >
constexpr bool is_header_ptr_v = is_header_ptr<T>::value
template<typename T >
constexpr bool is_header_v = is_header<T>::value
template<typename T >
constexpr bool is_gain_ref_v = is_gain_ref<T>::value
template<typename T >
constexpr bool is_gain_ptr_v = is_gain_ptr<T>::value
template<typename T >
constexpr bool is_gain_v = is_gain<T>::value
Function Documentation
to_body()
template<class T > std::enable_if_t<is_body_v<T>, datagram::IDatagramBody&> autd::core::type_traits::to_body (T && body)
Definition at line 113 of file type_traits.hpp.
Referenced by autd::Controller::send().
to_gain()
template<class T > std::enable_if_t<is_gain_v<T>, Gain&> autd::core::type_traits::to_gain (T && gain)
Definition at line 121 of file type_traits.hpp.
Referenced by autd::gain::Grouped::add(), autd::core::GainSequence::add(), autd::Controller::STMController::StreamCommaInputSTM::operator,(), and autd::Controller::STMController::StreamCommaInputSTM::operator=().
to_header()
template<class T > std::enable_if_t<is_header_v<T>, datagram::IDatagramHeader&> autd::core::type_traits::to_header (T && header)
Definition at line 105 of file type_traits.hpp.
Referenced by autd::Controller::send().
Variable Documentation
is_body_ptr_v
template<typename T > constexpr bool autd::core::type_traits::is_body_ptr_v = is_body_ptr<T>::value inline constexpr
Definition at line 51 of file type_traits.hpp.
is_body_ref_v
template<typename T > constexpr bool autd::core::type_traits::is_body_ref_v = is_body_ref<T>::value inline constexpr
Definition at line 44 of file type_traits.hpp.
is_body_v
template<typename T > constexpr bool autd::core::type_traits::is_body_v = is_body<T>::value inline constexpr
Definition at line 58 of file type_traits.hpp.
is_gain_ptr_v
template<typename T > constexpr bool autd::core::type_traits::is_gain_ptr_v = is_gain_ptr<T>::value inline constexpr
Definition at line 95 of file type_traits.hpp.
is_gain_ref_v
template<typename T > constexpr bool autd::core::type_traits::is_gain_ref_v = is_gain_ref<T>::value inline constexpr
Definition at line 88 of file type_traits.hpp.
is_gain_v
template<typename T > constexpr bool autd::core::type_traits::is_gain_v = is_gain<T>::value inline constexpr
Definition at line 102 of file type_traits.hpp.
is_header_ptr_v
template<typename T > constexpr bool autd::core::type_traits::is_header_ptr_v = is_header_ptr<T>::value inline constexpr
Definition at line 73 of file type_traits.hpp.
is_header_ref_v
template<typename T > constexpr bool autd::core::type_traits::is_header_ref_v = is_header_ref<T>::value inline constexpr
Definition at line 66 of file type_traits.hpp.
is_header_v
template<typename T > constexpr bool autd::core::type_traits::is_header_v = is_header<T>::value inline constexpr
Definition at line 80 of file type_traits.hpp.