name: Doxygen

on:
  push:
    branches: [ master, doc ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --force --recursive

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'
    - name: Setup mdbook-katex
      uses: magicgh/mdbook-katex-action@v1
      with:
        version: 'latest'
    - run: |
        cd book
        MDBOOK_BOOK__src=src/en mdbook build --dest-dir book/en
        MDBOOK_BOOK__src=src/jp mdbook build --dest-dir book/jp
    - name: mv mdbook doc
      run: |
        mkdir -p doc/book
        sudo mv ./book/book/en/html ./doc/book/en
        sudo mv ./book/book/jp/html ./doc/book/jp

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc
